[project]
name = "gludd-profile-dev-ansible"
version = "0"
requires-python = ">=3.11"
dependencies = [
    "ansible-core>=2.19.11,<2.20; python_version < '3.12'",
    "ansible-core>=2.21.2,<2.22; python_version >= '3.12'",
    "pytest-ansible>=24.0.0",
    "molecule>=24.0.0",
    "molecule-plugins[docker]>=25.8.12",
    "ansible-lint>=24.0.0",
]

[tool.uv]
package = false
