"""Database module — session management, repositories, models, migrations."""

__all__ = (
    "AuditEventModel",
    "AuditEventRepository",
    "AuditEventType",
    "Base",
    "BenchmarkRepository",
    "BenchmarkResultModel",
    "BucketLeaseModel",
    "ConcurrencyError",
    "InvalidTransitionError",
    "ProjectModel",
    "ProjectRepository",
    "PromptProfileModel",
    "PromptProfileRepository",
    "QueueModel",
    "QueueRepository",
    "TaskDecisionModel",
    "TaskReturnModel",
    "TaskReturnRepository",
    "TodoEventModel",
    "TodoModel",
    "TodoRepository",
    "VariableNamespaceModel",
    "VariableNamespaceRepository",
    "VariableValueModel",
    "create_async_session_factory",
    "ensure_tables",
    "get_alembic_config",
    "get_async_session",
    "get_default_db_url",
    "init_async_engine",
    "init_engine_from_config",
    "is_sqlite_url",
    "json_dumps",
    "run_wal_pragmas",
    "seed_initial_queues",
    "stamp_head",
)

from general_ludd.db.migrations import get_alembic_config, stamp_head
from general_ludd.db.models import (
    AuditEventModel,
    AuditEventType,
    Base,
    BenchmarkResultModel,
    BucketLeaseModel,
    ProjectModel,
    PromptProfileModel,
    QueueModel,
    TaskDecisionModel,
    TaskReturnModel,
    TodoEventModel,
    TodoModel,
    VariableNamespaceModel,
    VariableValueModel,
)
from general_ludd.db.repository import (
    AuditEventRepository,
    BenchmarkRepository,
    ConcurrencyError,
    InvalidTransitionError,
    ProjectRepository,
    PromptProfileRepository,
    QueueRepository,
    TaskReturnRepository,
    TodoRepository,
    VariableNamespaceRepository,
)
from general_ludd.db.session import (
    create_async_session_factory,
    ensure_tables,
    get_async_session,
    get_default_db_url,
    init_async_engine,
    init_engine_from_config,
    is_sqlite_url,
    json_dumps,
    run_wal_pragmas,
    seed_initial_queues,
)
