"""Repository implementations for the agentic harness."""
from __future__ import annotations

import contextlib
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any, cast

from sqlalchemy import select
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from general_ludd.db.models import (
    AgentMessageModel,
    AuditEventModel,
    AuditEventType,
    BenchmarkResultModel,
    FeatureModel,
    FeatureStatus,
    ProjectModel,
    PromptProfileModel,
    QueueModel,
    RoleRunModel,
    SpendRecordModel,
    TaskReturnModel,
    TodoEventModel,
    TodoModel,
    VariableNamespaceModel,
    VariableValueModel,
)
from general_ludd.schemas.todo import TodoStatus

VALID_TRANSITIONS: dict[TodoStatus, set[TodoStatus]] = {
    TodoStatus.BACKLOG: {TodoStatus.QUEUED},
    TodoStatus.QUEUED: {TodoStatus.ACTIVE, TodoStatus.FAILED, TodoStatus.BLOCKED},
    TodoStatus.ACTIVE: {
        TodoStatus.COMPLETE, TodoStatus.FAILED, TodoStatus.BLOCKED,
        TodoStatus.REVIEWING_RETURN, TodoStatus.MANUAL_HOLD,
        TodoStatus.NEEDS_MORE_WORK, TodoStatus.QUEUED,
    },
    TodoStatus.REVIEWING_RETURN: {
        TodoStatus.COMPLETE, TodoStatus.NEEDS_MORE_WORK,
        TodoStatus.FAILED, TodoStatus.BLOCKED, TodoStatus.MANUAL_HOLD,
    },
    TodoStatus.NEEDS_MORE_WORK: {TodoStatus.QUEUED, TodoStatus.ACTIVE},
    TodoStatus.MANUAL_HOLD: {TodoStatus.QUEUED, TodoStatus.ACTIVE},
    TodoStatus.BLOCKED: {TodoStatus.QUEUED},
    TodoStatus.FAILED: {TodoStatus.QUEUED},
    TodoStatus.COMPLETE: set(),
}


# Fields that callers are permitted to set via TodoRepository.create().
# Excludes auto-managed columns (id, version, created_at, updated_at) to
# prevent mass-assignment of internal state.
ALLOWED_TODO_CREATE_FIELDS: frozenset[str] = frozenset({
    "todo_id",
    "project_id",
    "title",
    "description",
    "status",
    "priority",
    "queue",
    "tags",
    "risk_level",
    "work_type",
    "resource_profile",
    "parent_todo_id",
    "child_todo_ids",
    "acceptance_criteria",
    "test_commands",
    "molecule_scenarios",
    "molecule_evidence_refs",
    "coverage_requirements",
    "dependencies",
    "created_by",
    "assigned_agent",
    "model_profile",
    "prompt_profile",
    "worktree",
    "branch_name",
    "artifacts",
    "evidence_refs",
    "plan_artifact",
    "confidence",
    "manual_hold_reason",
    "approval_policy",
    "completed_at",
})

# Maximum UTF-8 byte length for any single string field on a TodoModel create.
_TODO_STR_FIELD_MAX_BYTES = 65536


class ConcurrencyError(Exception):
    pass


class InvalidTransitionError(ConcurrencyError):
    pass


def _is_locked_error(exc: OperationalError) -> bool:
    """True when an OperationalError is SQLite's transient 'database is locked'.

    SQLite has no row-level locks, so under concurrent claimers a guarded UPDATE
    can raise SQLITE_BUSY -> OperationalError('database is locked') instead of
    simply affecting zero rows. That is a *lost race*, not a real fault: the
    losing claimer should skip the row, exactly as it would on rowcount == 0.
    """
    msg = str(getattr(exc, "orig", exc)).lower()
    return "database is locked" in msg or "database table is locked" in msg


class TodoRepository:
    # D-28: Fields that callers must not supply in create() — they are set by the
    # DB/ORM (the autoincrement primary key `id`, `created_at`, `updated_at`) or must
    # start at a fixed value (version=1).  Accepting them would let callers forge the
    # database primary key or skip version accounting.
    #
    # NOTE: `todo_id` is intentionally NOT here. It is an APPLICATION-assigned business
    # identifier (e.g. "TODO-001", generated by the /api/todos router or supplied by a
    # caller), set at creation time — distinct from the DB primary key `id`. Rejecting
    # it at create() broke every legitimate create path (the router and direct repo
    # callers both supply it). The real-primary-key forgery risk is covered by `id`.
    _IMMUTABLE_FIELDS: frozenset[str] = frozenset(
        {"id", "version", "created_at", "updated_at"}
    )
    # D-28: Maximum byte length for text columns.  Prevents callers from storing
    # arbitrarily large blobs through the create() path.
    _MAX_TEXT_BYTES: int = 65_536  # 64 KiB

    def __init__(self, session: AsyncSession, project_id: str | None = None) -> None:
        self._session = session
        self._project_id = project_id

    @classmethod
    def scoped(cls, session: AsyncSession, project_id: str) -> TodoRepository:
        """Return a repository pre-scoped to *project_id*.

        Every read/write method that accepts ``project_id`` will fall back to
        this scope when the caller passes ``project_id=None`` (the default).
        This prevents the silent cross-tenant query that the unscoped constructor
        allows.  Admin/cross-tenant callers should use the plain constructor (or
        pass an explicit ``project_id`` override per-call).
        """
        return cls(session, project_id=project_id)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_pid(self, project_id: str | None) -> str | None:
        """Return *project_id* if explicitly supplied, else fall back to the
        instance scope.  ``None`` is only propagated when the instance was not
        scoped (admin / cross-tenant path)."""
        return project_id if project_id is not None else self._project_id

    @classmethod
    def _validate_create_data(cls, todo_data: dict[str, Any]) -> None:
        """Raise ValueError if *todo_data* contains immutable fields or oversized
        text values (D-28).  Called before mass-assigning data to TodoModel so
        callers cannot forge primary keys, manipulate version counters, or store
        arbitrarily large blobs."""
        bad_fields = cls._IMMUTABLE_FIELDS & todo_data.keys()
        if bad_fields:
            raise ValueError(
                f"create() rejected: these fields are immutable and must not be "
                f"supplied by callers: {sorted(bad_fields)}"
            )
        for key, value in todo_data.items():
            if isinstance(value, str) and len(value.encode()) > cls._MAX_TEXT_BYTES:
                raise ValueError(
                    f"create() rejected: field '{key}' exceeds the "
                    f"{cls._MAX_TEXT_BYTES}-byte limit "
                    f"({len(value.encode())} bytes)"
                )

    async def create(self, todo_data: dict[str, Any]) -> TodoModel:
        # D-28: validate before mass-assignment so callers cannot forge primary
        # keys, skip version accounting, or store oversized blobs.
        self._validate_create_data(todo_data)
        todo = TodoModel(**todo_data)
        # D-28: enforce version=1 regardless of what the caller passed (already
        # blocked above, but belt-and-suspenders guard for future callers).
        todo.version = 1
        self._session.add(todo)
        await self._session.flush()
        return todo

    async def get_by_id(self, todo_id: str, project_id: str | None = None) -> TodoModel | None:
        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel).where(TodoModel.todo_id == todo_id)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def update(
        self,
        todo_id: str,
        updates: dict[str, Any],
        expected_version: int,
        project_id: str | None = None,
    ) -> TodoModel:
        from sqlalchemy import update as _update

        _pid = self._resolve_pid(project_id)
        todo = await self.get_by_id(todo_id, project_id=_pid)
        if todo is None:
            raise InvalidTransitionError(f"Todo {todo_id} not found")
        if todo.version != expected_version:
            raise ConcurrencyError(f"Version mismatch: expected {expected_version}, actual {todo.version}")
        now = datetime.now(UTC)
        # Guarded conditional UPDATE: the version read above can go stale before
        # this write commits. Carry the version (and scope) into the WHERE clause
        # so a concurrent writer at the same version makes one of us affect zero
        # rows -> ConcurrencyError, instead of silently losing an update.
        guard = (
            _update(TodoModel)
            .where(
                TodoModel.id == todo.id,
                TodoModel.version == expected_version,
            )
        )
        if _pid is not None:
            guard = guard.where(TodoModel.project_id == _pid)
        guard = guard.values(**updates, version=expected_version + 1, updated_at=now)
        res = await self._session.execute(guard)
        if (res.rowcount or 0) != 1:  # type: ignore[attr-defined]  # CursorResult at runtime
            raise ConcurrencyError(
                f"Lost update on todo {todo_id}: row changed concurrently "
                f"(expected version {expected_version})"
            )
        # Sync the in-memory ORM object to the committed values.
        for key, value in updates.items():
            setattr(todo, key, value)
        todo.version = expected_version + 1
        todo.updated_at = now
        await self._session.flush()
        return todo

    async def list_by_status(
        self,
        status: TodoStatus,
        project_id: str | None = None,
        limit: int | None = None,
    ) -> list[TodoModel]:
        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel).where(TodoModel.status == status.value)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        if limit is not None:
            stmt = stmt.limit(limit)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_all(
        self,
        queue: str | None = None,
        status: str | None = None,
        project_id: str | None = None,
        limit: int | None = None,
    ) -> list[TodoModel]:
        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel)
        if queue is not None:
            stmt = stmt.where(TodoModel.queue == queue)
        if status is not None:
            stmt = stmt.where(TodoModel.status == status)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        if limit is not None:
            stmt = stmt.limit(limit)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_by_work_type(
        self,
        work_type: str,
        project_id: str | None = None,
        limit: int | None = None,
    ) -> list[TodoModel]:
        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel).where(TodoModel.work_type == work_type)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        if limit is not None:
            stmt = stmt.limit(limit)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def claim_runnable(self, limit: int = 10, project_id: str | None = None) -> list[TodoModel]:
        """Claim QUEUED todos for execution with a guarded conditional UPDATE.

        SQLite has no row-level locking (``with_for_update`` is silently dropped),
        so the claim cannot rely on a lock. Instead, each candidate is flipped
        QUEUED->ACTIVE with an optimistic ``WHERE id=? AND status='queued' AND
        version=?`` UPDATE. Only the caller whose UPDATE affects a row (rowcount
        == 1) "wins" the claim; a caller that lost the race (rowcount == 0) skips
        the row, so every todo is returned to exactly one caller -> no double
        claim / double dispatch.
        """
        from sqlalchemy import update

        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel).where(TodoModel.status == TodoStatus.QUEUED.value)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        stmt = stmt.limit(limit)
        with contextlib.suppress(Exception):
            stmt = stmt.with_for_update(skip_locked=True)
        result = await self._session.execute(stmt)
        candidates = list(result.scalars().all())
        now = datetime.now(UTC)
        claimed: list[TodoModel] = []
        for todo in candidates:
            old_status = todo.status
            old_version = todo.version
            # Guarded conditional claim: transition only if the row is STILL
            # queued at the same version we read. Mirrors transition()'s
            # version/status guard so a concurrent claimer cannot also win.
            guard = (
                update(TodoModel)
                .where(
                    TodoModel.id == todo.id,
                    TodoModel.status == TodoStatus.QUEUED.value,
                    TodoModel.version == old_version,
                )
                .values(status=TodoStatus.ACTIVE.value, version=old_version + 1, updated_at=now)
            )
            try:
                res = await self._session.execute(guard)
            except OperationalError as exc:
                # SQLite has no row locks: a concurrent claimer can make the
                # guarded UPDATE raise SQLITE_BUSY ('database is locked') instead
                # of affecting zero rows. Treat that as a lost race exactly like
                # rowcount == 0 — refresh our stale copy and skip — so "loser
                # skips" still holds and a transient busy never aborts the claim.
                if not _is_locked_error(exc):
                    raise
                with contextlib.suppress(Exception):
                    await self._session.refresh(todo)
                continue
            if (res.rowcount or 0) != 1:  # type: ignore[attr-defined]  # CursorResult at runtime
                # Lost the race: another caller already claimed this row. Drop our
                # stale in-memory copy and skip it so it is never returned twice.
                await self._session.refresh(todo)
                continue
            # We won: sync the in-memory ORM object to the committed values.
            todo.status = TodoStatus.ACTIVE.value
            todo.version = old_version + 1
            todo.updated_at = now
            evt = TodoEventModel(
                todo_id=todo.todo_id,
                event_type="status_change",
                old_status=old_status,
                new_status=TodoStatus.ACTIVE.value,
                actor="claim_runnable",
                reason="Claimed for execution",
            )
            self._session.add(evt)
            claimed.append(todo)
        await self._session.flush()
        return claimed

    async def count_active(self, project_id: str | None = None) -> int:
        from sqlalchemy import func
        _pid = self._resolve_pid(project_id)
        stmt = select(func.count()).select_from(TodoModel).where(
            TodoModel.status == TodoStatus.ACTIVE.value
        )
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        result = await self._session.execute(stmt)
        return result.scalar() or 0

    async def status_summary(self, project_id: str | None = None) -> dict[str, Any]:
        """Aggregate todo facts: counts by status / queue / work_type, oldest age,
        backlog size. Reused by the /api/facts aggregation endpoint."""
        _pid = self._resolve_pid(project_id)
        stmt = select(TodoModel)
        if _pid is not None:
            stmt = stmt.where(TodoModel.project_id == _pid)
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        by_status: dict[str, int] = {}
        by_queue: dict[str, int] = {}
        by_work_type: dict[str, int] = {}
        oldest_created: datetime | None = None
        for r in rows:
            by_status[r.status] = by_status.get(r.status, 0) + 1
            by_queue[r.queue] = by_queue.get(r.queue, 0) + 1
            by_work_type[r.work_type] = by_work_type.get(r.work_type, 0) + 1
            created = r.created_at
            if created is not None:
                if created.tzinfo is None:
                    created = created.replace(tzinfo=UTC)
                if oldest_created is None or created < oldest_created:
                    oldest_created = created
        oldest_age_seconds: float | None = None
        if oldest_created is not None:
            oldest_age_seconds = (datetime.now(UTC) - oldest_created).total_seconds()
        backlog = by_status.get(TodoStatus.BACKLOG.value, 0) + by_status.get(
            TodoStatus.QUEUED.value, 0
        )
        return {
            "total": len(rows),
            "by_status": by_status,
            "by_queue": by_queue,
            "by_work_type": by_work_type,
            "oldest_age_seconds": oldest_age_seconds,
            "backlog_size": backlog,
        }

    async def transition(
        self,
        todo_id: str,
        new_status: TodoStatus,
        expected_version: int,
        project_id: str | None = None,
    ) -> TodoModel:
        from sqlalchemy import update as _update

        _pid = self._resolve_pid(project_id)
        todo = await self.get_by_id(todo_id, project_id=_pid)
        if todo is None:
            raise InvalidTransitionError(f"Todo {todo_id} not found")
        if todo.version != expected_version:
            raise ConcurrencyError(f"Version mismatch: expected {expected_version}, actual {todo.version}")
        current = TodoStatus(todo.status)
        allowed = VALID_TRANSITIONS.get(current, set())
        if new_status not in allowed:
            raise InvalidTransitionError(f"Invalid transition: {current.value} -> {new_status.value}")
        now = datetime.now(UTC)
        # Guarded conditional UPDATE keyed on the version AND the status we
        # validated the transition against: a concurrent writer that moved the
        # row out from under us (changing version or status) makes this affect
        # zero rows -> ConcurrencyError, never a silent lost transition.
        guard = (
            _update(TodoModel)
            .where(
                TodoModel.id == todo.id,
                TodoModel.version == expected_version,
                TodoModel.status == current.value,
            )
        )
        if _pid is not None:
            guard = guard.where(TodoModel.project_id == _pid)
        guard = guard.values(
            status=new_status.value, version=expected_version + 1, updated_at=now
        )
        res = await self._session.execute(guard)
        if (res.rowcount or 0) != 1:  # type: ignore[attr-defined]  # CursorResult at runtime
            raise ConcurrencyError(
                f"Lost transition on todo {todo_id}: row changed concurrently "
                f"(expected version {expected_version}, status {current.value})"
            )
        todo.status = new_status.value
        todo.version = expected_version + 1
        todo.updated_at = now
        await self._session.flush()
        return todo


class TaskReturnRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(self, data: dict[str, Any]) -> TaskReturnModel:
        row = TaskReturnModel(**data)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get_by_id(self, return_id: str) -> TaskReturnModel | None:
        stmt = select(TaskReturnModel).where(TaskReturnModel.return_id == return_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def work_summary(self, project_id: str | None = None) -> dict[str, Any]:
        """In-flight/claimed task-return counts by status / queue / work_type.

        Task returns represent dispatched work; this is the "work" facet of
        /api/facts. Reused, not duplicated, by the facts endpoint."""
        stmt = select(TaskReturnModel)
        if project_id is not None:
            stmt = stmt.where(TaskReturnModel.project_id == project_id)
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        by_status: dict[str, int] = {}
        by_queue: dict[str, int] = {}
        by_work_type: dict[str, int] = {}
        for r in rows:
            by_status[r.status] = by_status.get(r.status, 0) + 1
            by_queue[r.queue] = by_queue.get(r.queue, 0) + 1
            by_work_type[r.work_type] = by_work_type.get(r.work_type, 0) + 1
        return {
            "total": len(rows),
            "by_status": by_status,
            "by_queue": by_queue,
            "by_work_type": by_work_type,
        }

    async def history_summary(
        self, project_id: str | None = None, recent_limit: int = 10
    ) -> dict[str, Any]:
        """Recent returns + success/failure rates (exit_code 0 == success)."""
        stmt = select(TaskReturnModel)
        if project_id is not None:
            stmt = stmt.where(TaskReturnModel.project_id == project_id)
        stmt = stmt.order_by(TaskReturnModel.created_at.desc())
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        total = len(rows)
        successes = sum(1 for r in rows if r.exit_code == 0)
        failures = total - successes
        recent = [
            {
                "return_id": r.return_id,
                "playbook": r.playbook,
                "status": r.status,
                "exit_code": r.exit_code,
                "created_at": str(r.created_at) if r.created_at else None,
            }
            for r in rows[:recent_limit]
        ]
        return {
            "total_returns": total,
            "success_count": successes,
            "failure_count": failures,
            "success_rate": (successes / total) if total else 0.0,
            "recent": recent,
        }

    async def claim_unreviewed(self, project_id: str | None = None, limit: int = 10) -> list[TaskReturnModel]:
        """Claim 'created' task-returns for review with a guarded conditional UPDATE.

        TaskReturnModel has no version column, so the optimistic guard is on
        ``status`` alone: each candidate is flipped 'created'->'claimed_for_review'
        with ``WHERE id=? AND status='created'``. Only the caller whose UPDATE
        affects a row (rowcount == 1) claims it; a loser (rowcount == 0) skips it.
        This makes each return claimed by exactly one caller -> no double-review.
        """
        from sqlalchemy import update

        stmt = select(TaskReturnModel).where(TaskReturnModel.status == "created")
        if project_id is not None:
            stmt = stmt.where(TaskReturnModel.project_id == project_id)
        stmt = stmt.order_by(TaskReturnModel.created_at.asc()).limit(limit)
        result = await self._session.execute(stmt)
        candidates = list(result.scalars().all())
        now = datetime.now(UTC)
        claimed: list[TaskReturnModel] = []
        for row in candidates:
            guard = (
                update(TaskReturnModel)
                .where(
                    TaskReturnModel.id == row.id,
                    TaskReturnModel.status == "created",
                )
                .values(status="claimed_for_review", updated_at=now)
            )
            try:
                res = await self._session.execute(guard)
            except OperationalError as exc:
                # SQLITE_BUSY under concurrent claimers == a lost race, not a
                # fault: skip the row just as we would on rowcount == 0 so each
                # return is still claimed by exactly one caller.
                if not _is_locked_error(exc):
                    raise
                with contextlib.suppress(Exception):
                    await self._session.refresh(row)
                continue
            if (res.rowcount or 0) != 1:  # type: ignore[attr-defined]  # CursorResult at runtime
                # Lost the race: another caller already claimed this return.
                await self._session.refresh(row)
                continue
            row.status = "claimed_for_review"
            row.updated_at = now
            claimed.append(row)
        await self._session.flush()
        return claimed


class AuditEventRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        event_type: str,
        entity_type: str,
        entity_id: str,
        project_id: str | None = None,
        details: str | None = None,
    ) -> AuditEventModel:
        if project_id is None:
            raise ValueError(
                "project_id is required for audit events — "
                "NULL project_id silently orphans the event from its project"
            )
        row = AuditEventModel(
            event_type=event_type,
            entity_type=entity_type,
            entity_id=entity_id,
            project_id=project_id,
            details=details or "{}",
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def record_typed(
        self,
        event_type: AuditEventType,
        entity_type: str,
        entity_id: str,
        project_id: str | None = None,
        details: dict[str, Any] | None = None,
    ) -> AuditEventModel:
        """Record an audit event from the typed AuditEventType taxonomy.

        Serializes ``details`` to JSON and delegates to :meth:`create`. This is
        the typed entry point the event loop uses so audit rows carry values
        from the AuditEventType enum rather than ad-hoc magic strings.
        """
        import json as _json

        return await self.create(
            event_type=event_type.value,
            entity_type=entity_type,
            entity_id=entity_id,
            project_id=project_id,
            details=_json.dumps(details) if details is not None else None,
        )

    async def list_by_entity(self, entity_type: str, entity_id: str, limit: int = 50) -> list[AuditEventModel]:
        stmt = (
            select(AuditEventModel)
            .where(AuditEventModel.entity_type == entity_type, AuditEventModel.entity_id == entity_id)
            .order_by(AuditEventModel.created_at.desc())
            .limit(limit)
        )
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_by_project(self, project_id: str, limit: int = 50) -> list[AuditEventModel]:
        stmt = (
            select(AuditEventModel)
            .where(AuditEventModel.project_id == project_id)
            .order_by(AuditEventModel.created_at.desc())
            .limit(limit)
        )
        result = await self._session.execute(stmt)
        return list(result.scalars().all())


class VariableNamespaceRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def load_vars_for_project(self, project_id: str | None) -> dict[str, str]:
        stmt = (
            select(VariableValueModel)
            .join(VariableNamespaceModel)
            .where(
                (VariableNamespaceModel.project_id == project_id)
                | (VariableNamespaceModel.project_id.is_(None))
            )
            .order_by(
                VariableNamespaceModel.project_id.is_(None).desc()
            )
        )
        result = await self._session.execute(stmt)
        rows = result.scalars().all()
        result_dict: dict[str, str] = {}
        for row in rows:
            result_dict[row.key] = row.value
        return result_dict

    async def create_namespace(self, namespace: str, project_id: str | None = None) -> VariableNamespaceModel:
        row = VariableNamespaceModel(namespace=namespace, project_id=project_id)
        self._session.add(row)
        await self._session.flush()
        return row

    async def set_var(
        self, namespace: str, key: str, value: str, project_id: str | None = None
    ) -> VariableValueModel:
        from sqlalchemy.dialects.sqlite import insert as sqlite_insert

        # Resolve (or atomically create) the namespace. get-then-insert here is a
        # TOCTOU race on the (namespace, project_id) unique key: two concurrent
        # first-writers both see ns is None and both INSERT -> IntegrityError.
        # ON CONFLICT DO NOTHING on the unique constraint makes the insert a no-op
        # for the loser, who then re-reads the winner's row.
        stmt = select(VariableNamespaceModel).where(
            VariableNamespaceModel.namespace == namespace,
            VariableNamespaceModel.project_id == project_id,
        )
        ns = (await self._session.execute(stmt)).scalar_one_or_none()
        if ns is None:
            ns_insert = (
                sqlite_insert(VariableNamespaceModel)
                .values(namespace=namespace, project_id=project_id)
                .on_conflict_do_nothing(
                    index_elements=["namespace", "project_id"]
                )
            )
            await self._session.execute(ns_insert)
            await self._session.flush()
            ns = (await self._session.execute(stmt)).scalar_one()

        # Upsert the value on the (namespace_id, key) unique key. on_conflict_do_update
        # closes the get-then-insert TOCTOU: a concurrent first-write no longer
        # raises IntegrityError (and is no longer silently lost) — last writer wins.
        now = datetime.now(UTC)
        val_insert = (
            sqlite_insert(VariableValueModel)
            .values(namespace_id=ns.id, key=key, value=value, updated_at=now)
            .on_conflict_do_update(
                index_elements=["namespace_id", "key"],
                set_={"value": value, "updated_at": now},
            )
        )
        await self._session.execute(val_insert)
        await self._session.flush()
        row = (
            await self._session.execute(
                select(VariableValueModel).where(
                    VariableValueModel.namespace_id == ns.id,
                    VariableValueModel.key == key,
                )
            )
        ).scalar_one()
        # on_conflict_do_update bypasses the identity map; refresh so a previously
        # loaded value row reflects the just-committed value.
        await self._session.refresh(row)
        return row


class BenchmarkRepository:
    def __init__(
        self,
        session: AsyncSession | None = None,
        session_factory: async_sessionmaker[AsyncSession] | None = None,
    ) -> None:
        self._session = session
        self._session_factory = session_factory

    async def _execute_with_session(self, fn: Callable[[AsyncSession], Any]) -> Any:
        if self._session_factory is not None:
            async with self._session_factory() as session, session.begin():
                    result = await fn(session)
                    if hasattr(result, "_sa_instance_state"):
                        session.expunge(result)
                    return result
        if self._session is not None:
            return await fn(self._session)
        raise RuntimeError("BenchmarkRepository: no session or session_factory")

    async def record_result(self, data: dict[str, Any]) -> BenchmarkResultModel:
        async def _do(session: AsyncSession) -> BenchmarkResultModel:
            row = BenchmarkResultModel(**data)
            session.add(row)
            await session.flush()
            return row
        return cast(BenchmarkResultModel, await self._execute_with_session(_do))

    async def get_aggregate_scores(self, task_type: str | None = None) -> list[dict[str, Any]]:
        async def _do(session: AsyncSession) -> list[dict[str, Any]]:
            from sqlalchemy import func
            stmt = (
                select(
                    BenchmarkResultModel.prompt_profile_id,
                    BenchmarkResultModel.model_profile_id,
                    BenchmarkResultModel.task_type,
                    func.avg(BenchmarkResultModel.completion_score).label("avg_completion"),
                    func.avg(BenchmarkResultModel.code_quality_score).label("avg_quality"),
                    func.avg(BenchmarkResultModel.instruction_adherence_score).label("avg_instruction"),
                    func.avg(BenchmarkResultModel.token_efficiency_score).label("avg_efficiency"),
                    func.count().label("sample_count"),
                    func.avg(BenchmarkResultModel.cost_usd).label("avg_cost"),
                    func.avg(
                        BenchmarkResultModel.completion_score * 0.4
                        + BenchmarkResultModel.code_quality_score * 0.3
                        + BenchmarkResultModel.instruction_adherence_score * 0.2
                        + BenchmarkResultModel.token_efficiency_score * 0.1
                    ).label("composite_score"),
                )
                .where(BenchmarkResultModel.success.is_(True))
                .group_by(
                    BenchmarkResultModel.prompt_profile_id,
                    BenchmarkResultModel.model_profile_id,
                    BenchmarkResultModel.task_type,
                )
            )
            if task_type is not None:
                stmt = stmt.where(BenchmarkResultModel.task_type == task_type)
            result = await session.execute(stmt)
            rows = result.all()
            return [
                {
                    "prompt_profile_id": r.prompt_profile_id,
                    "model_profile_id": r.model_profile_id,
                    "task_type": r.task_type,
                    "avg_completion": r.avg_completion,
                    "avg_quality": r.avg_quality,
                    "avg_instruction": r.avg_instruction,
                    "avg_efficiency": r.avg_efficiency,
                    "sample_count": r.sample_count,
                    "avg_cost": r.avg_cost,
                    "composite_score": getattr(r, "composite_score", None),
                }
                for r in rows
            ]
        return cast("list[dict[str, Any]]", await self._execute_with_session(_do))

    async def get_best_for_task(self, task_type: str, min_samples: int = 3) -> list[dict[str, Any]]:
        scores = await self.get_aggregate_scores(task_type=task_type)
        filtered = [s for s in scores if s["sample_count"] >= min_samples]
        filtered.sort(key=lambda s: s.get("composite_score", 0) or 0, reverse=True)
        return filtered

    async def get_model_scores(self, model_profile_id: str) -> list[BenchmarkResultModel]:
        async def _do(session: AsyncSession) -> list[BenchmarkResultModel]:
            stmt = (
                select(BenchmarkResultModel)
                .where(BenchmarkResultModel.model_profile_id == model_profile_id)
                .order_by(BenchmarkResultModel.created_at.desc())
            )
            result = await session.execute(stmt)
            return list(result.scalars().all())
        return cast("list[BenchmarkResultModel]", await self._execute_with_session(_do))

    async def list_recent(self, limit: int = 50) -> list[BenchmarkResultModel]:
        async def _do(session: AsyncSession) -> list[BenchmarkResultModel]:
            stmt = (
                select(BenchmarkResultModel)
                .order_by(BenchmarkResultModel.created_at.desc())
                .limit(limit)
            )
            result = await session.execute(stmt)
            return list(result.scalars().all())
        return cast("list[BenchmarkResultModel]", await self._execute_with_session(_do))


class PromptProfileRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def upsert(self, data: dict[str, Any]) -> PromptProfileModel:
        from sqlalchemy.dialects.sqlite import insert as sqlite_insert

        # Upsert on the unique ``name`` key. The old get-then-insert was a TOCTOU
        # race: two concurrent first-writers for the same name both saw None and
        # both INSERTed -> IntegrityError (one write lost). on_conflict_do_update
        # makes the conflicting write an UPDATE instead, so concurrent first-writes
        # converge (last writer wins) with no IntegrityError.
        now = datetime.now(UTC)
        values = {**data, "updated_at": now}
        update_cols = {k: v for k, v in values.items() if k not in ("id", "name")}
        stmt = (
            sqlite_insert(PromptProfileModel)
            .values(**values)
            .on_conflict_do_update(index_elements=["name"], set_=update_cols)
        )
        await self._session.execute(stmt)
        await self._session.flush()
        row = await self.get_by_name(data["name"])
        assert row is not None  # just upserted
        # Core INSERT ... ON CONFLICT bypasses the ORM identity map; refresh any
        # already-loaded instance so callers see the committed (updated) values.
        await self._session.refresh(row)
        return row

    async def get_by_name(self, name: str) -> PromptProfileModel | None:
        stmt = select(PromptProfileModel).where(PromptProfileModel.name == name)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_by_id(self, profile_id: str) -> PromptProfileModel | None:
        stmt = select(PromptProfileModel).where(PromptProfileModel.id == profile_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list_all(self) -> list[PromptProfileModel]:
        stmt = select(PromptProfileModel)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_by_source(self, source: str) -> list[PromptProfileModel]:
        stmt = select(PromptProfileModel).where(PromptProfileModel.source == source)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_for_task_type(self, task_type: str) -> list[PromptProfileModel]:
        import json as _json
        stmt = select(PromptProfileModel)
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        out: list[PromptProfileModel] = []
        for row in rows:
            try:
                types = _json.loads(row.task_types or "[]")
            except Exception:
                types = []
            # Empty list means "match all task types"
            if not types or task_type in types:
                out.append(row)
        return out


class QueueRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(self, data: dict[str, Any]) -> QueueModel:
        row = QueueModel(**data)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get_by_name(self, name: str) -> QueueModel | None:
        stmt = select(QueueModel).where(QueueModel.queue_name == name)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list_all(self) -> list[QueueModel]:
        result = await self._session.execute(select(QueueModel))
        return list(result.scalars().all())

    async def list_enabled(self) -> list[QueueModel]:
        stmt = select(QueueModel).where(QueueModel.queue_enabled.is_(True))
        result = await self._session.execute(stmt)
        return list(result.scalars().all())


class ProjectRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(self, data: dict[str, Any]) -> ProjectModel:
        row = ProjectModel(**data)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get_by_id(self, project_id: str) -> ProjectModel | None:
        stmt = select(ProjectModel).where(ProjectModel.project_id == project_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list_active(self) -> list[ProjectModel]:
        stmt = select(ProjectModel).where(ProjectModel.active.is_(True))
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def deactivate(self, project_id: str) -> None:
        from sqlalchemy import update as _update

        # Single guarded UPDATE rather than read-then-mutate: the read-modify-write
        # form lets a concurrent writer's change be lost between the SELECT and the
        # ORM flush. Guarding on active == True also makes a double-deactivate a
        # detectable no-op instead of a silent clobber.
        guard = (
            _update(ProjectModel)
            .where(
                ProjectModel.project_id == project_id,
                ProjectModel.active.is_(True),
            )
            .values(active=False)
        )
        await self._session.execute(guard)
        await self._session.flush()
        # Keep any already-loaded ORM instance consistent with the committed row.
        project = await self.get_by_id(project_id)
        if project is not None:
            await self._session.refresh(project)


BROADCAST_RECIPIENT = "broadcast"


class AgentMessageRepository:
    """Persistence for the inter-agent message queue (AgentMessageModel)."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def send(self, data: dict[str, Any]) -> AgentMessageModel:
        row = AgentMessageModel(**data)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get_by_id(self, message_id: str) -> AgentMessageModel | None:
        stmt = select(AgentMessageModel).where(AgentMessageModel.id == message_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def inbox(
        self,
        recipient: str,
        unread_only: bool = True,
        include_broadcast: bool = True,
        project_id: str | None = None,
        limit: int = 100,
    ) -> list[AgentMessageModel]:
        """Return messages addressed to ``recipient`` (and broadcasts).

        Expired messages (past their ttl) are never returned.
        """
        from sqlalchemy import or_

        target: Any
        if include_broadcast:
            target = AgentMessageModel.recipient.in_([recipient, BROADCAST_RECIPIENT])
        else:
            target = AgentMessageModel.recipient == recipient
        stmt = select(AgentMessageModel).where(target)
        if unread_only:
            stmt = stmt.where(AgentMessageModel.read_at.is_(None))
        if project_id is not None:
            stmt = stmt.where(
                or_(
                    AgentMessageModel.project_id == project_id,
                    AgentMessageModel.project_id.is_(None),
                )
            )
        stmt = stmt.order_by(AgentMessageModel.created_at.asc()).limit(limit)
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        now = datetime.now(UTC)
        return [r for r in rows if not self._is_expired(r, now)]

    async def ack(self, message_id: str) -> AgentMessageModel | None:
        """Mark a message read. Returns the row, or None if it does not exist."""
        from sqlalchemy import update as _update

        row = await self.get_by_id(message_id)
        if row is None:
            return None
        # Guarded conditional UPDATE on read_at IS NULL: the read-then-mutate form
        # let two concurrent acks both see read_at None and both write, clobbering
        # the first ack's timestamp. Guarding on read_at IS NULL means only the
        # first ack writes; a later ack affects zero rows and leaves it untouched.
        now = datetime.now(UTC)
        guard = (
            _update(AgentMessageModel)
            .where(
                AgentMessageModel.id == message_id,
                AgentMessageModel.read_at.is_(None),
            )
            .values(read_at=now)
        )
        await self._session.execute(guard)
        await self._session.flush()
        await self._session.refresh(row)
        return row

    async def purge_expired(self) -> int:
        """Delete every message whose ttl has elapsed. Returns the count purged."""
        stmt = select(AgentMessageModel).where(AgentMessageModel.ttl_seconds.isnot(None))
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        now = datetime.now(UTC)
        purged = 0
        for row in rows:
            if self._is_expired(row, now):
                await self._session.delete(row)
                purged += 1
        if purged:
            await self._session.flush()
        return purged

    async def unread_counts(self, project_id: str | None = None) -> dict[str, int]:
        """Per-recipient unread counts (excludes expired). Used by /api/facts."""
        stmt = select(AgentMessageModel).where(AgentMessageModel.read_at.is_(None))
        if project_id is not None:
            from sqlalchemy import or_
            stmt = stmt.where(
                or_(
                    AgentMessageModel.project_id == project_id,
                    AgentMessageModel.project_id.is_(None),
                )
            )
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        now = datetime.now(UTC)
        counts: dict[str, int] = {}
        for row in rows:
            if self._is_expired(row, now):
                continue
            counts[row.recipient] = counts.get(row.recipient, 0) + 1
        return counts

    @staticmethod
    def _is_expired(row: AgentMessageModel, now: datetime) -> bool:
        if row.ttl_seconds is None:
            return False
        created = row.created_at
        if created is None:
            return False
        if created.tzinfo is None:
            created = created.replace(tzinfo=UTC)
        return (now - created).total_seconds() > row.ttl_seconds


class FeatureRepository:
    """Persistence for the feature database (FeatureModel).

    JSON (de)serialization happens at the repo boundary — callers pass / receive
    Python objects (lists/dicts); the DB stores JSON-in-Text as do PromptProfileModel
    and TodoModel.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _serialize(value: Any) -> str:
        import json as _json

        if isinstance(value, str):
            return value
        return _json.dumps(value)

    # ------------------------------------------------------------------
    # Write operations
    # ------------------------------------------------------------------

    async def upsert(self, data: dict[str, Any]) -> FeatureModel:
        """Insert or update a feature row, keyed by name (unique).

        Fields that are lists/dicts in ``data`` are serialized to JSON before
        being written to the DB.  The returned model has JSON-string columns.
        """
        from sqlalchemy.dialects.sqlite import insert as sqlite_insert

        json_fields = {"acceptance_criteria", "evidence"}
        serialized: dict[str, Any] = {}
        for key, val in data.items():
            if key in json_fields:
                serialized[key] = self._serialize(val)
            else:
                serialized[key] = val

        # Upsert on the unique ``name`` key. get-then-insert was a TOCTOU race
        # (two concurrent first-writes -> IntegrityError, one silently lost);
        # on_conflict_do_update turns the conflicting write into an UPDATE so
        # concurrent first-writes converge instead of raising.
        update_cols = {k: v for k, v in serialized.items() if k not in ("id", "name")}
        stmt = sqlite_insert(FeatureModel).values(**serialized)
        if update_cols:
            stmt = stmt.on_conflict_do_update(
                index_elements=["name"], set_=update_cols
            )
        else:
            stmt = stmt.on_conflict_do_nothing(index_elements=["name"])
        await self._session.execute(stmt)
        await self._session.flush()
        row = await self.get_by_name(data["name"])
        assert row is not None  # just upserted
        # The core INSERT ... ON CONFLICT bypasses the ORM identity map, so a row
        # already loaded this session is stale after the UPDATE — refresh it.
        await self._session.refresh(row)
        return row

    async def set_status(
        self,
        feature_id: str,
        status: FeatureStatus,
        detail: dict[str, Any] | None = None,
        verified_at: datetime | None = None,
    ) -> FeatureModel:
        """Update status, optional verified_at, and persist the verify-detail JSON."""
        import json as _json

        from sqlalchemy import update as _update

        row = await self.get_by_id(feature_id)
        if row is None:
            raise KeyError(f"Feature {feature_id!r} not found")
        # Single guarded UPDATE keyed on id instead of read-modify-write: the
        # ORM dirty-write form lets a concurrent status write be lost between the
        # SELECT above and the flush. Only the columns actually supplied are set.
        values: dict[str, Any] = {"status": status.value}
        if verified_at is not None:
            values["verified_at"] = verified_at
        if detail is not None:
            values["last_verify_detail"] = _json.dumps(detail)
        guard = (
            _update(FeatureModel)
            .where(FeatureModel.id == feature_id)
            .values(**values)
        )
        res = await self._session.execute(guard)
        if (res.rowcount or 0) != 1:  # type: ignore[attr-defined]  # CursorResult at runtime
            raise KeyError(f"Feature {feature_id!r} not found")
        await self._session.flush()
        await self._session.refresh(row)
        return row

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    async def get_by_name(self, name: str) -> FeatureModel | None:
        stmt = select(FeatureModel).where(FeatureModel.name == name)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_by_id(self, feature_id: str) -> FeatureModel | None:
        stmt = select(FeatureModel).where(FeatureModel.id == feature_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list_all(self) -> list[FeatureModel]:
        result = await self._session.execute(select(FeatureModel))
        return list(result.scalars().all())

    async def list_by_status(self, status: FeatureStatus) -> list[FeatureModel]:
        stmt = select(FeatureModel).where(FeatureModel.status == status.value)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def list_by_category(self, category: str) -> list[FeatureModel]:
        stmt = select(FeatureModel).where(FeatureModel.category == category)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())


class SpendRepository:
    """Persistence for rolling-window spend records.

    Each row represents one spend event recorded by :class:`SpendLimiter`.
    ``ts`` is an epoch float (e.g. from ``time.monotonic()`` or
    ``time.time()``); the rolling-window math compares timestamps as plain
    floats.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(
        self,
        ts: float,
        cost_usd: float,
        kind: str,
        project_id: str | None = None,
        model: str | None = None,
    ) -> SpendRecordModel:
        """Persist a spend event and return the new row.

        Args:
            ts:         Epoch float timestamp of the event.
            cost_usd:   Amount spent in USD.
            kind:       Resource kind (e.g. ``"token"``, ``"infra"``).
            project_id: Optional project scope.
            model:      Optional model identifier.

        Returns:
            The newly created :class:`SpendRecordModel` instance.
        """
        row = SpendRecordModel(
            ts=ts,
            cost_usd=cost_usd,
            kind=kind,
            project_id=project_id,
            model=model,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_since(
        self,
        since_epoch: float,
        project_id: str | None = None,
    ) -> list[SpendRecordModel]:
        """Return all records with ``ts >= since_epoch``.

        Args:
            since_epoch: Lower bound for ``ts`` (inclusive).
            project_id:  When set, restrict to records for this project.

        Returns:
            List of :class:`SpendRecordModel` rows ordered by ``ts`` ascending.
        """
        stmt = select(SpendRecordModel).where(SpendRecordModel.ts >= since_epoch)
        if project_id is not None:
            stmt = stmt.where(SpendRecordModel.project_id == project_id)
        stmt = stmt.order_by(SpendRecordModel.ts.asc())
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def total_since(
        self,
        since_epoch: float,
        project_id: str | None = None,
    ) -> float:
        """Sum of ``cost_usd`` for all records with ``ts >= since_epoch``.

        Args:
            since_epoch: Lower bound for ``ts`` (inclusive).
            project_id:  When set, restrict to records for this project.

        Returns:
            Total spend in USD (0.0 when no matching records).
        """
        from sqlalchemy import func

        stmt = select(func.sum(SpendRecordModel.cost_usd)).where(
            SpendRecordModel.ts >= since_epoch
        )
        if project_id is not None:
            stmt = stmt.where(SpendRecordModel.project_id == project_id)
        result = await self._session.execute(stmt)
        total: float | None = result.scalar_one_or_none()
        return float(total) if total is not None else 0.0


class RoleRunRepository:
    """Persistence for per-project role-run records.

    Each row records that a named role executed once for a given project.
    ``count_by_role`` returns the {role: run_count} map used by the
    accounting ledger.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def record(self, project_id: str | None, role: str) -> RoleRunModel:
        """Insert a single role-run record."""
        row = RoleRunModel(project_id=project_id, role=role)
        self._session.add(row)
        await self._session.flush()
        return row

    async def count_by_role(self, project_id: str | None = None) -> dict[str, int]:
        """Return {role: count} for the given project_id (or all if None)."""
        stmt = select(RoleRunModel)
        if project_id is not None:
            stmt = stmt.where(RoleRunModel.project_id == project_id)
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        counts: dict[str, int] = {}
        for row in rows:
            counts[row.role] = counts.get(row.role, 0) + 1
        return counts

    async def list_all(self, project_id: str | None = None) -> list[RoleRunModel]:
        stmt = select(RoleRunModel)
        if project_id is not None:
            stmt = stmt.where(RoleRunModel.project_id == project_id)
        result = await self._session.execute(stmt)
        return list(result.scalars().all())
