---
version: 3
images:
  base_image:
    name: docker.io/library/python:3.11.13-slim@sha256:9bffe4353b925a1656688797ebc68f9c525e79b1d377a764d232182a519eeec4
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
options:
  package_manager_path: /usr/bin/apt-get
  user: root
