---
version: 3
images:
  base_image:
    name: docker.io/library/python:3.11.13-slim@sha256:a9981becc57482c8bcc84aa6cbf5cbdfad0e421351e32a097b70d709ed9ec44d
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
options:
  package_manager_path: /usr/bin/apt-get
  user: root

