# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['src/agentic_harness/cli.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('config', 'config'),
        ('templates', 'templates'),
        ('playbooks', 'playbooks'),
    ],
    hiddenimports=[
        'agentic_harness',
        'agentic_harness.cli',
        'agentic_harness.daemon',
        'agentic_harness.worker.app',
        'agentic_harness.event_loop.loop',
        'agentic_harness.event_loop.lease',
        'agentic_harness.ansible.runner',
        'agentic_harness.ansible.core_runner',
        'agentic_harness.ansible.templating',
        'agentic_harness.models.gateway',
        'agentic_harness.models.router',
        'agentic_harness.db.models',
        'agentic_harness.db.repository',
        'agentic_harness.secrets.manager',
        'agentic_harness.mcp.client',
        'agentic_harness.mcp.transport',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'mypy', 'ruff', 'pre_commit', 'molecule', 'ansible_lint'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='hottentot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
