variable "image" {
  description = "llama.cpp server container image."
  type        = string
  default     = "ghcr.io/ggerganov/llama.cpp:server"
}

variable "gpus" {
  description = "Exact GPUs exposed by the selected fixed Azure VM shape."
  type        = number
  default     = 1

  validation {
    condition     = contains([1, 2, 4], var.gpus)
    error_message = "Azure NC A100/H100 shapes support 1, 2, or 4 GPUs."
  }
}

variable "model" {
  description = "Model path or identifier served by llama.cpp."
  type        = string
}

variable "region" {
  description = "Azure region selected by the read-only preflight."
  type        = string
  default     = "eastus"
}

variable "instance_type" {
  description = "Exact Azure accelerator VM SKU resolved by gludd."
  type        = string

  validation {
    condition = contains([
      "Standard_NC4as_T4_v3",
      "Standard_NC24ads_A100_v4",
      "Standard_NC48ads_A100_v4",
      "Standard_NC96ads_A100_v4",
      "Standard_NC40ads_H100_v5",
      "Standard_NC80adis_H100_v5",
    ], var.instance_type)
    error_message = "instance_type must be a release-supported Azure accelerator SKU."
  }
}

variable "extra_args" {
  description = "Additional validated llama.cpp arguments."
  type        = string
  default     = ""
}

variable "max_cost_usd" {
  description = "Maximum intended deployment spend."
  type        = number

  validation {
    condition     = var.max_cost_usd > 0
    error_message = "max_cost_usd must be positive."
  }
}

variable "timeout_minutes" {
  description = "Persisted daemon teardown TTL, already bounded by known hourly price."
  type        = number

  validation {
    condition     = var.timeout_minutes > 0
    error_message = "timeout_minutes must be positive."
  }
}

variable "allowed_cidr" {
  description = "Only CIDR permitted to reach SSH and the inference endpoint."
  type        = string
  default     = "127.0.0.1/32"
}

variable "ssh_public_key_path" {
  description = "Local public-key path; private key material never enters Terraform."
  type        = string
  default     = "~/.ssh/id_ed25519.pub"
}

variable "disk_size_gb" {
  description = "Premium OS disk size."
  type        = number
  default     = 100
}

variable "use_spot" {
  description = "Use an Azure Spot VM; failed/evicted deployments remain Terraform-owned."
  type        = bool
  default     = true
}

variable "deployment_name" {
  description = "Unique resource-group and resource prefix generated by gludd."
  type        = string

  validation {
    condition     = can(regex("^gludd-[a-z0-9-]{3,42}$", var.deployment_name))
    error_message = "deployment_name must be a gludd-prefixed lowercase identifier."
  }
}
