-- Generated by general_ludd.networking.networking. Edit role inputs, not this file.
local proto = Proto(
    "{{ networking__dissector_name }}",
    "{{ networking__dissector_name | replace('_', ' ') | title }}"
)

{% for field in networking__dissector_fields | default([]) %}
local field_{{ field.name }} = ProtoField.{{ field.type | default('uint8') }}(
    "{{ networking__dissector_name }}.{{ field.name }}",
    "{{ field.description | default(field.name) | replace('"', '\\"') }}"
)
{% endfor %}

proto.fields = {
{% for field in networking__dissector_fields | default([]) %}
    field_{{ field.name }},
{% endfor %}
}

function proto.dissector(buffer, packet_info, tree)
    local captured = buffer:len()
    packet_info.cols.protocol:set("{{ networking__dissector_name | upper }}")
    local subtree = tree:add(proto, buffer())
{% for field in networking__dissector_fields | default([]) %}
    if captured >= {{ field.offset | default(0) | int + field.size | default(1) | int }} then
        subtree:add(
            field_{{ field.name }},
            buffer({{ field.offset | default(0) | int }}, {{ field.size | default(1) | int }})
        )
    end
{% endfor %}
    return captured
end

DissectorTable.get("udp.port"):add({{ networking__dissector_port | int }}, proto)
