"""LaTeX generation role helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class LatexConfig:
    document_class: str = "article"
    font_size: str = "11pt"
    title: str = "Generated Document"
    author: str = "Agentic Harness"


def generate_paper(config: LatexConfig) -> str:
    bs = chr(92)
    lines = [
        f"{bs}documentclass[{config.font_size}]{{{config.document_class}}}",
        f"{bs}title{{{config.title}}}",
        f"{bs}author{{{config.author}}}",
        f"{bs}begin{{document}}",
        f"{bs}maketitle",
        f"{bs}section{{Overview}}",
        "This document was generated by gludd physics latex.",
        f"{bs}end{{document}}",
    ]
    return "\n".join(lines) + "\n"


def render_equation(equation: str, label: str = "eq:generated") -> str:
    bs = chr(92)
    lines = [
        f"{bs}begin{{equation}}",
        equation,
        f"{bs}label{{{label}}}",
        f"{bs}end{{equation}}",
    ]
    return "\n".join(lines) + "\n"


def render_align(equations: list[str]) -> str:
    bs = chr(92)
    body = [f"  {equation}" for equation in equations]
    return "\n".join([f"{bs}begin{{align}}", *body, f"{bs}end{{align}}", ""])


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    bs = chr(92)
    col_spec = "l" * len(headers)
    rendered = [f"{bs}begin{{tabular}}{{{col_spec}}}", " & ".join(headers) + f" {bs}{bs}"]
    for row in rows:
        rendered.append(" & ".join(row) + f" {bs}{bs}")
    rendered.append(f"{bs}end{{tabular}}")
    return "\n".join(rendered) + "\n"


def write_latex_output(content: str, output_dir: str, filename: str = "document.tex") -> Path:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    out = path / filename
    out.write_text(content, encoding="utf-8")
    return out
