"""E2E: Validate ALL 18 terraform stacks (9 vllm + 9 llamacpp, incl 2 qemu).

Iterates every stack under ``infra/terraform/stacks/``, auto-generates
terraform.tfvars from declared variables, runs ``terraform/opentofu init``
+ ``validate``, and exercises ``DeploymentManager.plan()`` for each
provider-engine combination.  Never applies.

Skips gracefully when the terraform/tofu binary is missing or when a
stack's init fails (network, provider credentials, unsupported platform).
"""

from __future__ import annotations

import asyncio
import re
import shutil
import subprocess
from pathlib import Path
from typing import ClassVar

import pytest

STACKS_DIR = Path("infra/terraform/stacks")
ALL_STACK_NAMES: list[str] = sorted(
    d.name for d in STACKS_DIR.iterdir() if d.is_dir()
)
VLLM_STACKS: list[str] = [s for s in ALL_STACK_NAMES if s.endswith("-vllm")]
LLAMACPP_STACKS: list[str] = [s for s in ALL_STACK_NAMES if s.endswith("-llamacpp")]
QEMU_STACKS: list[str] = [s for s in ALL_STACK_NAMES if s.startswith("qemu-")]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _infra_binary() -> str | None:
    for name in ("tofu", "terraform"):
        if shutil.which(name):
            return name
    return None


@pytest.fixture(scope="session")
def infra_binary() -> str:
    binary = _infra_binary()
    if binary is None:
        pytest.skip("terraform/tofu not on PATH")
    return binary


def _strip_comments(text: str) -> str:
    return re.sub(r"//.*", "", text)  # strip single-line comments


def _parse_variables(stack_dir: Path) -> dict[str, str]:
    """Extract variable names and defaults from variables.tf.

    Returns a dict mapping variable name → value (original default or
    a synthetic value for required-but-missing vars).
    """
    vars_tf = stack_dir / "variables.tf"
    if not vars_tf.exists():
        return {}
    text = _strip_comments(vars_tf.read_text())

    var_blocks = re.findall(
        r'variable\s+"(\w+)"\s*\{\s*(.+?)\n\}', text, re.DOTALL,
    )
    # Map variable name → (type_str, default_str | None)
    variables: dict[str, tuple[str, str | None]] = {}
    for var_name, body in var_blocks:
        type_match = re.search(r'type\s*=\s*(\w+(?:\([^)]*\))?)', body)
        var_type = type_match.group(1) if type_match else "string"
        default_match = re.search(
            r'default\s*=\s*(.+?)(?:\n\s*\}|\n\}|\n\s*\n|\n\Z)',
            body,
        )
        if default_match:
            raw = default_match.group(1).strip().rstrip(",")
            if raw.startswith('"') and raw.endswith('"'):
                raw = raw[1:-1]
            variables[var_name] = (var_type, raw)
        else:
            variables[var_name] = (var_type, None)

    result: dict[str, str] = {}
    for name, (vtype, default) in variables.items():
        if default is not None:
            result[name] = default
        else:
            result[name] = _synthetic_default(name, vtype)
    return result


def _tfvar_value(val: str) -> str:
    escaped = val.replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${")
    return f'"{escaped}"'


def _write_tfvars(stack_dir: Path) -> Path:
    vars_dict = _parse_variables(stack_dir)
    lines: list[str] = [
        "# Auto-generated by test_terraform_all_stacks_valid.py",
        "# DO NOT COMMIT",
    ]
    for name, value in vars_dict.items():
        if value.lower() == "true":
            lines.append(f"{name} = true")
        elif value.lower() == "false":
            lines.append(f"{name} = false")
        elif _looks_numeric(value):
            lines.append(f"{name} = {value}")
        else:
            lines.append(f"{name} = {_tfvar_value(value)}")
    tfvars_path = stack_dir / "terraform.auto.tfvars"
    tfvars_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return tfvars_path


def _copy_terraform_tree(destination: Path) -> Path:
    """Copy mutable Terraform inputs outside the checkout and return stacks."""
    copied_root = destination / "terraform"
    shutil.copytree(
        STACKS_DIR.parent.resolve(),
        copied_root,
        ignore=shutil.ignore_patterns(
            ".terraform",
            ".terraform.lock.hcl",
            "terraform.auto.tfvars",
            "*.tfstate",
            "*.tfstate.*",
        ),
    )
    return copied_root / "stacks"


@pytest.fixture(scope="session")
def mutable_stacks_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Provide a worker-owned Terraform tree for all mutating E2E commands."""
    return _copy_terraform_tree(tmp_path_factory.mktemp("terraform-e2e"))


def _looks_numeric(val: str) -> bool:
    try:
        int(val)
        return True
    except ValueError:
        try:
            float(val)
            return True
        except ValueError:
            return False


def _synthetic_default(var_name: str, var_type: str) -> str:
    if var_type.startswith("number"):
        return "1"
    if var_type.startswith("bool"):
        return "false"
    if var_type.startswith("list"):
        return "[]"
    if var_type.startswith("map"):
        return "{}"
    lower = var_name.lower()
    if "ssh" in lower or "key" in lower:
        return "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITest test@example.com"
    if "ami" in lower:
        return "ami-TESTEDNON"
    if "subnet" in lower:
        return "subnet-TESTEDNON"
    if "cidr" in lower:
        return "10.0.0.0/16"
    if "model" in lower:
        return "meta-llama/Llama-3.2-1B-Instruct"
    if "image" in lower or "container" in lower:
        return "alpine:latest"
    if "url" in lower:
        return "https://example.com"
    if "region" in lower:
        return "us-east-1"
    if "kubeconfig" in lower:
        return "~/.kube/config"
    return "test-value"


def _run_infra(
    binary: str, args: list[str], cwd: Path, timeout: int = 120,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [binary, *args],
        capture_output=True,
        text=True,
        cwd=str(cwd),
        timeout=timeout,
    )


# ---------------------------------------------------------------------------
# Structural tests — no binary needed
# ---------------------------------------------------------------------------


class TestStackEnumeration:
    """Verify the stack directory contains the expected 18 stacks."""

    def test_exactly_18_stacks(self) -> None:
        assert len(ALL_STACK_NAMES) == 18, (
            f"Expected 18 stacks, found {len(ALL_STACK_NAMES)}: {ALL_STACK_NAMES}"
        )

    def test_9_vllm_stacks(self) -> None:
        assert len(VLLM_STACKS) == 9

    def test_9_llamacpp_stacks(self) -> None:
        assert len(LLAMACPP_STACKS) == 9

    def test_2_qemu_stacks(self) -> None:
        assert len(QEMU_STACKS) == 2

    def test_qemu_are_subset_of_vllm_plus_llamacpp(self) -> None:
        for qs in QEMU_STACKS:
            assert qs in VLLM_STACKS or qs in LLAMACPP_STACKS

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_every_stack_has_main_tf(self, stack: str) -> None:
        assert (STACKS_DIR / stack / "main.tf").exists()

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_every_stack_has_variables(self, stack: str) -> None:
        assert (STACKS_DIR / stack / "variables.tf").exists()

    @pytest.mark.parametrize("stack", QEMU_STACKS)
    def test_qemu_stacks_have_outputs(self, stack: str) -> None:
        assert (STACKS_DIR / stack / "outputs.tf").exists()

    @pytest.mark.parametrize("stack", VLLM_STACKS + LLAMACPP_STACKS)
    def test_every_stack_has_module_reference(self, stack: str) -> None:
        main = (STACKS_DIR / stack / "main.tf").read_text()
        assert "module" in main, f"{stack} main.tf has no module references"


class TestTfvarsGeneration:
    """Structural checks on auto-generated tfvars (no binary needed)."""

    def test_mutable_tree_isolated_from_checkout(self, tmp_path: Path) -> None:
        copied_stacks = _copy_terraform_tree(tmp_path)

        assert copied_stacks != STACKS_DIR.resolve()
        assert (copied_stacks / "aws-vllm" / "main.tf").is_file()
        assert (copied_stacks.parent / "modules" / "vllm-server" / "main.tf").is_file()

    def test_generated_tfvars_stays_in_isolated_tree(self, tmp_path: Path) -> None:
        source_tfvars = STACKS_DIR / "aws-vllm" / "terraform.auto.tfvars"
        source_before = source_tfvars.read_bytes() if source_tfvars.exists() else None
        copied_stacks = _copy_terraform_tree(tmp_path)

        generated = _write_tfvars(copied_stacks / "aws-vllm")

        assert generated.is_relative_to(tmp_path)
        source_after = source_tfvars.read_bytes() if source_tfvars.exists() else None
        assert source_after == source_before

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_parse_variables_returns_non_empty(self, stack: str) -> None:
        vars_dict = _parse_variables(STACKS_DIR / stack)
        assert len(vars_dict) >= 1, f"{stack} has 0 parseable variables"

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_generated_tfvars_does_not_error(
        self,
        mutable_stacks_dir: Path,
        stack: str,
    ) -> None:
        _write_tfvars(mutable_stacks_dir / stack)

    def test_model_var_has_synthetic_default_when_required(self) -> None:
        vars_aws_vllm = _parse_variables(STACKS_DIR / "aws-vllm")
        assert "model" in vars_aws_vllm
        assert "Llama" in vars_aws_vllm["model"]


# ---------------------------------------------------------------------------
# Init + validate — requires terraform/tofu binary
# ---------------------------------------------------------------------------


@pytest.mark.skipif(_infra_binary() is None, reason="terraform/tofu not on PATH")
class TestAllStacksInitValidate:
    """Run init + validate on isolated copies of all 18 stacks.

    Auto.tfvars provides synthetic values for required variables.
    Stacks whose init fails (network, credentials, unsupported provider)
    are skipped individually.
    """

    _INIT_TIMEOUT = 300
    _VALIDATE_TIMEOUT = 60

    @staticmethod
    def _clean_dot_terraform(stack_dir: Path) -> None:
        dt = stack_dir / ".terraform"
        if dt.exists():
            shutil.rmtree(dt, ignore_errors=True)
        lck = stack_dir / ".terraform.lock.hcl"
        if lck.exists():
            lck.unlink(missing_ok=True)

    @staticmethod
    def _clean_tfvars(stack_dir: Path) -> None:
        tfvars = stack_dir / "terraform.auto.tfvars"
        if tfvars.exists():
            tfvars.unlink(missing_ok=True)

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_init_succeeds(
        self,
        infra_binary: str,
        mutable_stacks_dir: Path,
        stack: str,
    ) -> None:
        stack_dir = mutable_stacks_dir / stack
        try:
            _write_tfvars(stack_dir)
        except Exception:
            pytest.skip(f"tfvars generation failed for {stack}")

        self._clean_dot_terraform(stack_dir)
        try:
            result = _run_infra(
                infra_binary, ["init", "-input=false"],
                cwd=stack_dir, timeout=self._INIT_TIMEOUT,
            )
        except subprocess.TimeoutExpired:
            self._clean_tfvars(stack_dir)
            self._clean_dot_terraform(stack_dir)
            pytest.skip(f"{infra_binary} init timed out for {stack}")

        if result.returncode != 0:
            self._clean_tfvars(stack_dir)
            self._clean_dot_terraform(stack_dir)
            pytest.skip(
                f"{infra_binary} init skipped for {stack} "
                f"(rc={result.returncode}): {result.stderr[:400]}"
            )
        try:
            assert (stack_dir / ".terraform").exists()
        finally:
            self._clean_tfvars(stack_dir)

    @pytest.mark.parametrize("stack", ALL_STACK_NAMES)
    def test_validate_succeeds(
        self,
        infra_binary: str,
        mutable_stacks_dir: Path,
        stack: str,
    ) -> None:
        stack_dir = mutable_stacks_dir / stack
        _write_tfvars(stack_dir)

        if not (stack_dir / ".terraform").exists():
            init_result = _run_infra(
                infra_binary, ["init", "-input=false"],
                cwd=stack_dir, timeout=300,
            )
            if init_result.returncode != 0:
                self._clean_dot_terraform(stack_dir)
                self._clean_tfvars(stack_dir)
                pytest.skip(
                    f"{infra_binary} init failed for {stack} "
                    f"(rc={init_result.returncode}): {init_result.stderr[:400]}"
                )

        result = _run_infra(
            infra_binary, ["validate", "-json"],
            cwd=stack_dir, timeout=self._VALIDATE_TIMEOUT,
        )
        if result.returncode != 0:
            self._clean_dot_terraform(stack_dir)
            self._clean_tfvars(stack_dir)
        try:
            assert result.returncode == 0, (
                f"{infra_binary} validate failed for {stack} "
                f"(rc={result.returncode}):\n"
                f"stdout: {result.stdout[:500]}\n"
                f"stderr: {result.stderr[:500]}"
            )
        finally:
            self._clean_tfvars(stack_dir)

    def test_no_apply_run_any_stack(self, mutable_stacks_dir: Path) -> None:
        tfstate_counts = sum(
            1 for s in ALL_STACK_NAMES
            if (mutable_stacks_dir / s / "terraform.tfstate").exists()
        )
        assert tfstate_counts == 0, (
            "terraform.tfstate found — apply was run on one or more stacks"
        )

# ---------------------------------------------------------------------------
# DeploymentManager.plan() — async tests
# ---------------------------------------------------------------------------


@pytest.mark.skipif(_infra_binary() is None, reason="terraform/tofu not on PATH")
class TestDeploymentManagerPlan:
    """Exercise DeploymentManager.plan() for each provider-engine combo."""

    @pytest.fixture(autouse=True)
    def _dm(self) -> None:
        from general_ludd.config.binary_paths import BinaryPathResolver
        self._resolver = BinaryPathResolver()

    _PROVIDER_ENGINES: ClassVar[list[tuple[str, str]]] = [
        ("aws", "vllm"), ("aws", "llamacpp"),
        ("azure", "vllm"), ("azure", "llamacpp"),
        ("gcp", "vllm"), ("gcp", "llamacpp"),
        ("kubernetes", "vllm"), ("kubernetes", "llamacpp"),
        ("qemu", "vllm"), ("qemu", "llamacpp"),
        ("runpod", "vllm"), ("runpod", "llamacpp"),
        ("vast", "vllm"), ("vast", "llamacpp"),
        ("vsphere", "vllm"), ("vsphere", "llamacpp"),
    ]

    @pytest.mark.parametrize("provider,engine", _PROVIDER_ENGINES)
    def test_plan_returns_dict(self, provider: str, engine: str) -> None:
        from general_ludd.infra.compute import (
            ComputeConfig,
            ComputeProvider,
            GPUType,
            InferenceEngine,
        )
        from general_ludd.infra.deployment import DeploymentManager
        config = ComputeConfig(
            provider=ComputeProvider(provider),
            gpu_type=GPUType.T4,
            engine=InferenceEngine(engine),
            model_name="meta-llama/Llama-3.2-1B-Instruct",
            region="us-east-1",
        )
        dm = DeploymentManager(binary_paths=self._resolver)
        try:
            result = asyncio.run(dm.plan(config))
        except (RuntimeError, subprocess.TimeoutExpired) as exc:
            pytest.skip(f"plan({provider}/{engine}) failed: {exc}")
        assert isinstance(result, dict)
        assert "changes_present" in result
        assert result["returncode"] in (0, 2)

    def test_plan_24h_amd_mi250_special_case(self) -> None:
        from general_ludd.infra.compute import (
            ComputeConfig,
            ComputeProvider,
            GPUType,
            InferenceEngine,
        )
        from general_ludd.infra.deployment import DeploymentManager
        config = ComputeConfig(
            provider=ComputeProvider.VAST,
            gpu_type=GPUType.AMD_MI250,
            engine=InferenceEngine.LLAMACPP,
            model_name="meta-llama/Llama-3.2-1B-Instruct",
            gpu_count=8,
            max_cost_usd=8000,
            timeout_minutes=1440,
        )
        dm = DeploymentManager(binary_paths=self._resolver)
        try:
            result = asyncio.run(dm.plan(config))
        except (RuntimeError, subprocess.TimeoutExpired) as exc:
            pytest.skip(f"plan(24h-mi250) failed: {exc}")
        assert result["returncode"] in (0, 2)

    def test_deployment_manager_validate_aws_vllm(self) -> None:
        from general_ludd.infra.compute import (
            ComputeConfig,
            ComputeProvider,
            GPUType,
            InferenceEngine,
        )
        from general_ludd.infra.deployment import DeploymentManager
        config = ComputeConfig(
            provider=ComputeProvider.AWS,
            gpu_type=GPUType.T4,
            engine=InferenceEngine.VLLM,
            model_name="meta-llama/Llama-3.2-1B-Instruct",
        )
        dm = DeploymentManager(binary_paths=self._resolver)
        try:
            result = asyncio.run(dm.validate(config))
        except RuntimeError as exc:
            pytest.skip(f"validate(aws/vllm) failed: {exc}")
        assert result["returncode"] == 0

    def test_deployment_manager_validate_azure_containerapp_vllm(self, tmp_path: Path) -> None:
        from general_ludd.infra.compute import (
            ComputeConfig,
            ComputeProvider,
            GPUType,
            InferenceEngine,
        )
        from general_ludd.infra.deployment import DeploymentManager

        config = ComputeConfig(
            provider=ComputeProvider.AZURE,
            gpu_type=GPUType.T4,
            engine=InferenceEngine.VLLM,
            model_name="Qwen/Qwen2.5-0.5B-Instruct",
            region="eastus",
            deploy_type="containerapp",
            allowed_cidr="198.51.100.10/32",
        )
        dm = DeploymentManager(working_dir=str(tmp_path), binary_paths=self._resolver)

        result = asyncio.run(dm.validate(config))

        assert result["returncode"] == 0

    def test_deployment_manager_validate_qemu_llamacpp(self) -> None:
        from general_ludd.infra.compute import (
            ComputeConfig,
            ComputeProvider,
            GPUType,
            InferenceEngine,
        )
        from general_ludd.infra.deployment import DeploymentManager
        config = ComputeConfig(
            provider=ComputeProvider.QEMU,
            gpu_type=GPUType.T4,
            engine=InferenceEngine.LLAMACPP,
            model_name="models/qwen2.5-0.5b-Q4_K_M.gguf",
        )
        dm = DeploymentManager(binary_paths=self._resolver)
        try:
            result = asyncio.run(dm.validate(config))
        except RuntimeError as exc:
            pytest.skip(f"validate(qemu/llamacpp) failed: {exc}")
        assert result["returncode"] == 0


# ---------------------------------------------------------------------------
# QEMU stack validation
# ---------------------------------------------------------------------------


class TestQemuStackVariables:
    """QEMU stacks must be validatable without cloud credentials."""

    @pytest.mark.parametrize("stack", QEMU_STACKS)
    def test_all_required_vars_have_defaults_or_synthetics(self, stack: str) -> None:
        vars_dict = _parse_variables(STACKS_DIR / stack)
        for name, value in vars_dict.items():
            assert value is not None and len(value) > 0, (
                f"{stack} variable '{name}' has empty/missing default"
            )

    def test_qemu_vllm_ssh_key_gets_synthetic(self) -> None:
        vars_dict = _parse_variables(STACKS_DIR / "qemu-vllm")
        assert "ssh-ed25519" in vars_dict["ssh_public_key"]

    def test_qemu_llamacpp_ssh_key_gets_synthetic(self) -> None:
        vars_dict = _parse_variables(STACKS_DIR / "qemu-llamacpp")
        assert "ssh-ed25519" in vars_dict["ssh_public_key"]
