---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
platforms:
  - name: localhost
    ansible_connection: local
provisioner:
  name: ansible
  config_options:
    defaults:
      gathering: explicit
      connection: local
      interpreter_python: auto_silent
      host_key_checking: false
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - converge
    - idempotence
    - verify
