#!/usr/bin/env python3
"""cgi_wsgi — WSGI/ASGI config generator, socket path validator."""
import argparse
import os
import stat
import sys
from pathlib import Path


def validate_socket_path(socket_path):
    """Check that socket path directory exists and is writable."""
    result = {"valid": True, "errors": []}
    sp = Path(socket_path)
    parent = sp.parent
    if not parent.exists():
        result["valid"] = False
        result["errors"].append(f"Parent directory does not exist: {parent}")
    elif not os.access(parent, os.W_OK):
        result["valid"] = False
        result["errors"].append(f"Parent directory not writable: {parent}")
    if sp.exists():
        mode = sp.stat().st_mode
        if not stat.S_ISSOCK(mode):
            result["errors"].append(f"Path exists but is not a socket: {socket_path}")
    return result


def generate_wsgi_nginx_config(socket_path, app_module, processes, threads):
    return f"""\
# Generated by cgi_wsgi.py — WSGI gateway config
upstream app_server {{
    server unix:{socket_path} fail_timeout=0;
}}

server {{
    listen 80;
    server_name _;

    location / {{
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://app_server;
        proxy_read_timeout 120s;
    }}
}}
"""


def generate_asgi_nginx_config(socket_path, app_module, processes, threads):
    return f"""\
# Generated by cgi_wsgi.py — ASGI gateway config
upstream app_server {{
    server unix:{socket_path} fail_timeout=0;
}}

server {{
    listen 80;
    server_name _;

    location / {{
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://app_server;
        proxy_read_timeout 120s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
}}
"""


def generate_fastcgi_nginx_config(socket_path, app_module, processes, threads):
    return f"""\
# Generated by cgi_wsgi.py — FastCGI gateway config
server {{
    listen 80;
    server_name _;
    root /var/www/html;

    location ~ \\.php$ {{
        include fastcgi_params;
        fastcgi_pass unix:{socket_path};
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 60s;
    }}
}}
"""


GENERATORS = {
    "wsgi": generate_wsgi_nginx_config,
    "asgi": generate_asgi_nginx_config,
    "fastcgi": generate_fastcgi_nginx_config,
}


def main():
    parser = argparse.ArgumentParser(description="cgi_wsgi config tool")
    sub = parser.add_subparsers(dest="command")

    val_p = sub.add_parser("validate-socket")
    val_p.add_argument("--socket-path", required=True)

    gen_p = sub.add_parser("generate")
    gen_p.add_argument("--gateway-type", choices=["wsgi", "asgi", "fastcgi"],
                       required=True)
    gen_p.add_argument("--socket-path", required=True)
    gen_p.add_argument("--app-module", default="app:application")
    gen_p.add_argument("--processes", type=int, default=5)
    gen_p.add_argument("--threads", type=int, default=1)
    gen_p.add_argument("--output", help="file path to write config snippet")

    args = parser.parse_args()

    if args.command == "validate-socket":
        result = validate_socket_path(args.socket_path)
        print(f"valid={result['valid']}")
        for err in result["errors"]:
            print(f"error: {err}")
        sys.exit(0 if result["valid"] else 1)

    elif args.command == "generate":
        gen = GENERATORS.get(args.gateway_type)
        if not gen:
            print(f"Unknown gateway type: {args.gateway_type}", file=sys.stderr)
            sys.exit(1)
        config = gen(args.socket_path, args.app_module, args.processes,
                     args.threads)
        if args.output:
            Path(args.output).write_text(config)
            print(f"Written to {args.output}")
        else:
            print(config)


if __name__ == "__main__":
    main()
