#!/usr/bin/env python3
"""Frida instrumentation generator for the frida_instrument role.

Generates Frida JavaScript hook scripts and frida CLI invocations for
function interception, memory scanning, SSL pinning bypass, and runtime
tracing via the Stalker API. Report-only — does not invoke frida or attach
to any process.
"""
from __future__ import annotations

import argparse
import json
import shlex
import sys
from pathlib import Path

VALID_MODES = (
    "function_interception",
    "memory_scanning",
    "ssl_pinning_bypass",
    "tracing",
)

_MODES = {
    "function_interception": "Interceptor.attach hooks for function entry/exit",
    "memory_scanning": "Memory.scan over process ranges with pattern matching",
    "ssl_pinning_bypass": "SSL pinning bypass hooks for BoringSSL / Security.framework",
    "tracing": "Stalker.follow tracing of call/ret/exec events on main thread",
}


def _launcher(frida_tools_path: str) -> str:
    return "{}/frida".format(frida_tools_path.rstrip("/"))


_FUNCTION_INTERCEPTION_SCRIPT = """// Frida function interception harness
// Generated by gludd binary_re.frida_instrument (report-only)

var TARGETS = {targets_json};

function hookSymbol(symbolName) {{
    var addr = Module.findExportByName(null, symbolName);
    if (addr === null) {{
        console.log("[!] symbol not found: " + symbolName);
        return;
    }}
    Interceptor.attach(addr, {{
        onEnter: function (args) {{
            this.t0 = Date.now();
            console.log("[+] enter " + symbolName
                + " arg0=" + args[0].toString()
                + " arg1=" + args[1].toString());
        }},
        onLeave: function (retval) {{
            console.log("[+] leave " + symbolName
                + " ret=" + retval.toString()
                + " ms=" + (Date.now() - this.t0));
        }}
    }});
    console.log("[*] hooked " + symbolName + " @ " + addr);
}}

TARGETS.forEach(hookSymbol);
console.log("[*] interception harness installed; targets=" + TARGETS.length);
"""


def gen_function_interception(
    target: str, targets: list[str], process_spec: str
) -> dict:
    safe_targets = [t for t in targets if t]
    script = _FUNCTION_INTERCEPTION_SCRIPT.format(
        targets_json=json.dumps(safe_targets)
    )
    invocation = "{launcher} -l {{script}} -p {{pid}} -- {process}".format(
        launcher=shlex.quote(_launcher("/usr/local/bin")),
        process=shlex.quote(process_spec),
    )
    return {
        "script": script,
        "script_path": "/tmp/gludd-frida-intercept.js",
        "invocation": invocation,
        "process_spec": process_spec,
        "target_symbols": safe_targets,
    }


_MEMORY_SCAN_SCRIPT = """// Frida memory scanning harness
// Generated by gludd binary_re.frida_instrument (report-only)

var PATTERN = "{pattern}";
var HITS = 0;
var HIT_CAP = {hit_cap};

function scanRange(base, size) {{
    if (HITS >= HIT_CAP) return;
    Memory.scan(base, size, PATTERN, {{
        onMatch: function (address, size) {{
            HITS += 1;
            if (HITS <= HIT_CAP) {{
                console.log("[+] match @ " + address + " size=" + size);
            }}
        }},
        onError: function (reason) {{
            console.log("[!] scan error: " + reason);
        }},
        onComplete: function () {{
            console.log("[*] range done; hits=" + HITS);
        }}
    }});
}}

Process.enumerateRanges({{ protection: "rw-", coalesce: true }}).forEach(function (r) {{
    scanRange(r.base, r.size);
}});
console.log("[*] memory scan complete; total_hits=" + HITS + " cap=" + HIT_CAP);
"""


def gen_memory_scanning(
    target: str, pattern: str, hit_cap: int, process_spec: str
) -> dict:
    safe_pattern = pattern.replace('"', '\\"') or "AA BB CC DD"
    script = _MEMORY_SCAN_SCRIPT.format(
        pattern=safe_pattern, hit_cap=int(hit_cap)
    )
    invocation = "{launcher} -l {{script}} -- {process}".format(
        launcher=shlex.quote(_launcher("/usr/local/bin")),
        process=shlex.quote(process_spec),
    )
    return {
        "script": script,
        "script_path": "/tmp/gludd-frida-memory-scan.js",
        "invocation": invocation,
        "process_spec": process_spec,
        "pattern": safe_pattern,
        "hit_cap": int(hit_cap),
    }


_SSL_PINNING_SCRIPT = """// Frida SSL pinning bypass harness
// Generated by gludd binary_re.frida_instrument (report-only)
// Targets: BoringSSL (ssl_verify_peer_cert), Apple Security.framework
// (SecTrustEvaluate), and Java X509TrustManager.

function hookBoringSSL() {{
    var sym = Module.findExportByName(null, "ssl_verify_peer_cert");
    if (sym !== null) {{
        Interceptor.replace(sym, new NativeCallback(function (ssl, out, _) {{
            console.log("[+] ssl_verify_peer_cert bypassed");
            return 0;
        }}, "int", ["pointer", "pointer", "pointer"]));
        console.log("[*] hooked ssl_verify_peer_cert");
    }}
}}

function hookSecTrustEvaluate() {{
    var sym = Module.findExportByName("Security", "SecTrustEvaluate");
    if (sym !== null) {{
        Interceptor.attach(sym, {{
            onLeave: function (retval) {{
                retval.replace(0);
                console.log("[+] SecTrustEvaluate forced to errSecSuccess");
            }}
        }});
        console.log("[*] hooked SecTrustEvaluate");
    }}
}}

function hookJavaTrustManager() {{
    if (typeof Java !== "undefined" && Java.available) {{
        Java.perform(function () {{
            var X509TrustManager = Java.use("javax.net.ssl.X509TrustManager");
            var SSLContext = Java.use("javax.net.ssl.SSLContext");
            var TrustManager = Java.registerClass({{
                name: "org.gludd.NaiveTrustManager",
                implements: [X509TrustManager],
                methods: {{
                    checkClientTrusted: function () {{}},
                    checkServerTrusted: function () {{}},
                    getAcceptedIssuers: function () {{
                        return [];
                    }}
                }}
            }});
            SSLContext.init.overload(
                "[Ljavax.net.ssl.KeyManager;",
                "[Ljavax.net.ssl.TrustManager;",
                "java.security.SecureRandom"
            ).implementation = function (km, tm, sr) {{
                console.log("[+] SSLContext.init pinning bypassed");
                this.init(km, [TrustManager.$new()], sr);
            }};
            console.log("[*] hooked Java X509TrustManager");
        }});
    }}
}}

hookBoringSSL();
hookSecTrustEvaluate();
hookJavaTrustManager();
console.log("[*] SSL pinning bypass harness installed");
"""


def gen_ssl_pinning_bypass(target: str, process_spec: str) -> dict:
    script = _SSL_PINNING_SCRIPT
    invocation = "{launcher} -l {{script}} -- {process}".format(
        launcher=shlex.quote(_launcher("/usr/local/bin")),
        process=shlex.quote(process_spec),
    )
    return {
        "script": script,
        "script_path": "/tmp/gludd-frida-ssl-bypass.js",
        "invocation": invocation,
        "process_spec": process_spec,
        "hooks": [
            "ssl_verify_peer_cert",
            "SecTrustEvaluate",
            "X509TrustManager",
        ],
    }


_TRACING_SCRIPT = """// Frida Stalker tracing harness
// Generated by gludd binary_re.frida_instrument (report-only)

var EVENTS = {{ call: true, ret: {trace_ret}, exec: {trace_exec} }};
var CALL_LOG = [];
var CALL_CAP = {call_cap};

function onReceive(events) {{
    events.forEach(function (ev) {{
        if (CALL_LOG.length < CALL_CAP) {{
            CALL_LOG.push(ev);
        }}
    }});
}}

Stalker.follow(Process.mainThread.id, {{
    events: EVENTS,
    onReceive: function (events) {{
        var parsed = Stalker.parse(events);
        parsed.forEach(function (entry) {{
            if (CALL_LOG.length < CALL_CAP) {{
                CALL_LOG.push(entry);
            }}
        }});
        if (CALL_LOG.length % 100 === 0) {{
            console.log("[*] traced events=" + CALL_LOG.length);
        }}
    }}
}});

setTimeout(function () {{
    Stalker.unfollow(Process.mainThread.id);
    console.log("[*] tracing complete; events=" + CALL_LOG.length
        + " cap=" + CALL_CAP);
}}, {trace_ms});
"""


def gen_tracing(
    target: str,
    process_spec: str,
    trace_ms: int,
    trace_ret: bool,
    trace_exec: bool,
    call_cap: int,
) -> dict:
    script = _TRACING_SCRIPT.format(
        trace_ms=int(trace_ms),
        trace_ret=("true" if trace_ret else "false"),
        trace_exec=("true" if trace_exec else "false"),
        call_cap=int(call_cap),
    )
    invocation = "{launcher} -l {{script}} -- {process}".format(
        launcher=shlex.quote(_launcher("/usr/local/bin")),
        process=shlex.quote(process_spec),
    )
    return {
        "script": script,
        "script_path": "/tmp/gludd-frida-trace.js",
        "invocation": invocation,
        "process_spec": process_spec,
        "trace_ms": int(trace_ms),
        "trace_ret": bool(trace_ret),
        "trace_exec": bool(trace_exec),
        "call_cap": int(call_cap),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Frida instrumentation generator (report-only)"
    )
    parser.add_argument("--target", required=True, help="Target binary path")
    parser.add_argument("--mode", required=True, choices=VALID_MODES)
    parser.add_argument(
        "--process", default="",
        help="Process spec (name or PID) for frida to attach",
    )
    parser.add_argument(
        "--targets", default="open,read,write",
        help="Comma-separated function symbols (function_interception)",
    )
    parser.add_argument(
        "--pattern", default="",
        help="Hex byte pattern e.g. 'AA BB CC DD' (memory_scanning)",
    )
    parser.add_argument(
        "--hit-cap", type=int, default=1000,
        help="Max matches before memory scan stops",
    )
    parser.add_argument(
        "--trace-ms", type=int, default=5000,
        help="Stalker trace duration in ms (tracing)",
    )
    parser.add_argument(
        "--trace-ret", action="store_true",
        help="Trace return events (tracing)",
    )
    parser.add_argument(
        "--trace-exec", action="store_true",
        help="Trace exec events (tracing — noisy)",
    )
    parser.add_argument(
        "--call-cap", type=int, default=50000,
        help="Max traced events retained (tracing)",
    )
    parser.add_argument("--output", default="-", help="Output file (default stdout)")
    args = parser.parse_args()

    process_spec = args.process or args.target

    if args.mode == "function_interception":
        payload = gen_function_interception(
            args.target, args.targets.split(","), process_spec
        )
    elif args.mode == "memory_scanning":
        payload = gen_memory_scanning(
            args.target, args.pattern, args.hit_cap, process_spec
        )
    elif args.mode == "ssl_pinning_bypass":
        payload = gen_ssl_pinning_bypass(args.target, process_spec)
    elif args.mode == "tracing":
        payload = gen_tracing(
            args.target,
            process_spec,
            args.trace_ms,
            args.trace_ret,
            args.trace_exec,
            args.call_cap,
        )
    else:
        print(f"ERROR: unknown mode {args.mode}", file=sys.stderr)
        sys.exit(2)

    artifact = {
        "target": args.target,
        "mode": args.mode,
        "backend": "report-only",
        **payload,
    }

    text = json.dumps(artifact, indent=2)
    if args.output == "-":
        print(text)
    else:
        Path(args.output).write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
