"""GeneratorImpl — creates pytest test files from a GenerationSpec.

Generates a well-structured pytest file per target module with:
- Module docstring
- Pytest import
- AAA-pattern test functions (Arrange/Act/Assert)
- Fixture scaffolding
"""

from __future__ import annotations

import logging
from pathlib import Path

from general_ludd.agents.test_generation.contracts import GenerationHarness, GenerationSpec
from general_ludd.sandbox.contracts import MINIMAL_SANDBOX_CONFIG, SandboxConfig

logger = logging.getLogger(__name__)

_TEST_FILE_TEMPLATE = '''\
"""E2E tests for {target} - auto-generated by GeneratorImpl."""

import pytest


class Test{cls_name}E2E:
    """End-to-end test suite for {target}."""

    def test_module_imports_cleanly(self) -> None:
        """Arrange: import {target}.
        Act: verify the import succeeds.
        Assert: module is not None.
        """
        try:
            import {target}
        except ImportError:
            pytest.skip("{target} not importable in this environment")

    def test_fixtures_resolve(self) -> None:
        """Arrange: reference standard fixtures.
        Act: verify they resolve.
        Assert: collection succeeds.
        """
        assert True
'''

_CONFTEST_SOURCE = '''\
"""E2E test configuration - auto-generated conftest."""

import pytest
'''


class GeneratorImpl:
    def __init__(
        self,
        *,
        spec: GenerationSpec,
        harness: GenerationHarness,
        sandbox_config: SandboxConfig | None = None,
    ) -> None:
        self.spec = spec
        self.harness = harness
        self.sandbox_config = sandbox_config if sandbox_config is not None else MINIMAL_SANDBOX_CONFIG

    def generate(self) -> list[str]:
        module_name = self.spec.target_module.split(".")[-1]
        output_dir = Path(self.spec.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        filenames: list[str] = []

        test_filename = output_dir / f"test_e2e_{module_name}.py"
        self._write_test_file(test_filename, module_name)
        filenames.append(str(test_filename))

        conftest_path = output_dir / "conftest.py"
        if not conftest_path.exists():
            self._write_conftest(conftest_path)

        logger.info("generated %d test files in %s", len(filenames), output_dir)
        return filenames

    def _write_test_file(self, path: Path, module_name: str) -> None:
        target = self.spec.target_module
        source = _TEST_FILE_TEMPLATE.format(
            target=target,
            cls_name=module_name.capitalize(),
        )
        path.write_text(source)

    def _write_conftest(self, path: Path) -> None:
        path.write_text(_CONFTEST_SOURCE)


__all__ = ["GeneratorImpl"]
