---
driver:
  name: default
platforms: []
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/collections"
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
