"""Conflicts & treaties knowledge module for the governance collection.

Exposes active/ongoing conflicts, a treaty database, international courts,
and accessors that let an agent answer "which treaties bind country X?" or
"does court Y have jurisdiction over case type Z?".

Public surface::

    CONFLICT_TYPES       enum of 7 conflict categories
    ACTIVE_CONFLICTS     list of conflict dicts
    TREATY_DATABASE      list of treaty dicts
    INTERNATIONAL_COURTS list of court dicts

    lookup_conflict(region)                -> list[conflict dict]
    get_treaty(treaty_id)                  -> treaty dict | None
    get_treaty_parties(treaty_id)          -> list[str]
    get_treaty_obligations(country)        -> list[obligation dict]
    get_court_jurisdiction(court_id)       -> str | None
    check_court_jurisdiction(court_id, case_type) -> bool
"""

from __future__ import annotations

import enum
from typing import Any


class _ConflictMeta(enum.EnumMeta):
    def __contains__(cls, item: object) -> bool:
        if isinstance(item, cls):
            return True
        if isinstance(item, str):
            return item in {m.value for m in cls}
        return False


class ConflictType(enum.Enum, metaclass=_ConflictMeta):
    INTERSTATE = "interstate"
    INTRASTATE = "intrastate"
    ASYMMETRIC = "asymmetric"
    CYBER = "cyber"
    ECONOMIC = "economic"
    PROXY = "proxy"
    FROZEN = "frozen"


CONFLICT_TYPES = ConflictType


ACTIVE_CONFLICTS: list[dict[str, Any]] = [
    {
        "id": "russo_ukraine_war",
        "name": "Russo-Ukrainian War",
        "region": "Eastern Europe",
        "type": ConflictType.INTERSTATE,
        "parties": ["Russia", "Ukraine"],
        "status": "active",
    },
    {
        "id": "sudan_civil_war",
        "name": "Sudanese Civil War",
        "region": "East Africa",
        "type": ConflictType.INTRASTATE,
        "parties": ["Sudanese Armed Forces", "Rapid Support Forces"],
        "status": "active",
    },
    {
        "id": "myanmar_civil_war",
        "name": "Myanmar Civil War",
        "region": "Southeast Asia",
        "type": ConflictType.INTRASTATE,
        "parties": ["Myanmar military (Tatmadaw)", "Various ethnic armed organizations"],
        "status": "active",
    },
    {
        "id": "israel_hamas_war",
        "name": "Israel-Gaza War",
        "region": "Middle East",
        "type": ConflictType.ASYMMETRIC,
        "parties": ["Israel", "Hamas"],
        "status": "active",
    },
    {
        "id": "sahel_insurgency",
        "name": "Sahel Insurgency",
        "region": "West Africa",
        "type": ConflictType.ASYMMETRIC,
        "parties": ["Burkina Faso", "Mali", "Niger", "JNIM", "ISGS"],
        "status": "active",
    },
    {
        "id": "south_china_sea",
        "name": "South China Sea Dispute",
        "region": "East Asia",
        "type": ConflictType.PROXY,
        "parties": ["China", "Philippines", "Vietnam", "Malaysia", "Brunei"],
        "status": "frozen",
    },
    {
        "id": "korean_conflict",
        "name": "Korean Conflict",
        "region": "East Asia",
        "type": ConflictType.FROZEN,
        "parties": ["North Korea", "South Korea", "United States"],
        "status": "armistice",
    },
    {
        "id": "yemen_civil_war",
        "name": "Yemeni Civil War",
        "region": "Middle East",
        "type": ConflictType.PROXY,
        "parties": ["Hadi Government (internationally recognized)", "Houthi Movement", "Saudi Arabia", "Iran"],
        "status": "active",
    },
    {
        "id": "ethiopia_tigray_conflict",
        "name": "Tigray Conflict",
        "region": "East Africa",
        "type": ConflictType.INTRASTATE,
        "parties": ["Ethiopian Federal Government", "Tigray People's Liberation Front (TPLF)"],
        "status": "ceasefire",
    },
    {
        "id": "nagorno_karabakh",
        "name": "Nagorno-Karabakh Conflict",
        "region": "Caucasus",
        "type": ConflictType.FROZEN,
        "parties": ["Azerbaijan", "Armenia"],
        "status": "post_conflict",
    },
    {
        "id": "cyber_great_power",
        "name": "Great-Power Cyber Rivalry",
        "region": "Global",
        "type": ConflictType.CYBER,
        "parties": ["United States", "China", "Russia", "Iran", "North Korea"],
        "status": "ongoing",
    },
    {
        "id": "congo_kivu_conflict",
        "name": "Kivu Conflict (Eastern DRC)",
        "region": "Central Africa",
        "type": ConflictType.INTRASTATE,
        "parties": ["DRC Government", "M23", "ADF", "CODECO", "FDLR", "various militias"],
        "status": "active",
    },
    {
        "id": "venezuela_crisis",
        "name": "Venezuelan Political and Economic Crisis",
        "region": "South America",
        "type": ConflictType.ECONOMIC,
        "parties": ["Maduro Government", "Venezuelan Opposition", "United States", "Colombia"],
        "status": "ongoing",
    },
    {
        "id": "taiwan_strait",
        "name": "Taiwan Strait Tensions",
        "region": "East Asia",
        "type": ConflictType.FROZEN,
        "parties": ["China", "Taiwan", "United States"],
        "status": "frozen",
    },
    {
        "id": "belarus_unrest",
        "name": "Belarus Political Crisis",
        "region": "Eastern Europe",
        "type": ConflictType.INTRASTATE,
        "parties": ["Lukashenko Government", "Belarusian Opposition", "Russia"],
        "status": "ongoing",
    },
    {
        "id": "western_sahara",
        "name": "Western Sahara Conflict",
        "region": "North Africa",
        "type": ConflictType.FROZEN,
        "parties": ["Morocco", "Polisario Front", "Algeria", "Mauritania"],
        "status": "frozen",
    },
]


TREATY_DATABASE: list[dict[str, Any]] = [
    {
        "id": "geneva_conventions",
        "name": "Geneva Conventions of 1949",
        "subject": "international_humanitarian_law",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Russia",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Israel",
            "Iran",
            "Iraq",
            "Saudi Arabia",
            "Turkey",
            "Pakistan",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "North Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Romania",
            "Czech Republic",
            "Austria",
            "Greece",
            "Portugal",
            "Ireland",
            "Hungary",
            "Bulgaria",
            "Algeria",
            "Morocco",
            "Tunisia",
            "Libya",
            "Sudan",
            "Ethiopia",
            "Kenya",
            "Tanzania",
            "Uganda",
            "Ghana",
            "Ivory Coast",
            "Senegal",
            "Cameroon",
            "Angola",
            "Mozambique",
            "Zimbabwe",
            "Chile",
            "Colombia",
            "Peru",
            "Venezuela",
            "Ecuador",
            "Bolivia",
            "Paraguay",
            "Uruguay",
            "Cuba",
            "Dominican Republic",
            "Guatemala",
            "Honduras",
            "Nicaragua",
            "Costa Rica",
            "Panama",
            "Afghanistan",
            "Kazakhstan",
            "Uzbekistan",
            "Turkmenistan",
            "Azerbaijan",
            "Armenia",
            "Georgia",
            "Belarus",
            "Moldova",
            "Slovakia",
            "Slovenia",
            "Croatia",
            "Serbia",
            "Bosnia and Herzegovina",
            "North Macedonia",
            "Albania",
            "Montenegro",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Lebanon",
            "Jordan",
            "Syria",
            "Yemen",
            "Oman",
            "Qatar",
            "Bahrain",
            "Kuwait",
            "United Arab Emirates",
            "Cambodia",
            "Laos",
            "Malaysia",
            "Singapore",
            "Brunei",
            "Sri Lanka",
            "Maldives",
            "Nepal",
            "Bhutan",
            "Bangladesh",
            "Mongolia",
            "Papua New Guinea",
            "New Zealand",
            "Fiji",
            "Solomon Islands",
            "Vanuatu",
            "Samoa",
            "Tonga",
            "Tuvalu",
            "Kiribati",
            "Marshall Islands",
            "Micronesia",
            "Palau",
            "Nauru",
            "Tajikistan",
            "Kyrgyzstan",
            "Madagascar",
            "Mauritius",
            "Seychelles",
            "Comoros",
            "Djibouti",
            "Eritrea",
            "Somalia",
            "Central African Republic",
            "Chad",
            "Niger",
            "Mali",
            "Burkina Faso",
            "Togo",
            "Benin",
            "Burundi",
            "Rwanda",
            "Democratic Republic of the Congo",
            "Republic of the Congo",
            "Gabon",
            "Equatorial Guinea",
            "Sao Tome and Principe",
            "Lesotho",
            "Eswatini",
            "Botswana",
            "Namibia",
            "South Sudan",
            "Liberia",
            "Sierra Leone",
            "Guinea",
            "Guinea-Bissau",
            "The Gambia",
            "Mauritania",
            "Cape Verde",
            "Timor-Leste",
            "Bahamas",
            "Barbados",
            "Jamaica",
            "Trinidad and Tobago",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Antigua and Barbuda",
            "Dominica",
            "Saint Kitts and Nevis",
            "Grenada",
            "Belize",
            "Guyana",
            "Suriname",
            "Haiti",
            "San Marino",
            "Monaco",
            "Liechtenstein",
            "Andorra",
            "Vatican City",
            "Malta",
            "Cyprus",
            "Iceland",
            "Luxembourg",
        ],
        "enforcement": {
            "mechanism": "ICRC protective powers; universal jurisdiction for grave breaches",
            "body": "International Committee of the Red Cross",
        },
    },
    {
        "id": "paris_agreement",
        "name": "Paris Agreement on Climate Change",
        "subject": "climate_change",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Saudi Arabia",
            "Iran",
            "Iraq",
            "United Arab Emirates",
            "Qatar",
            "Kuwait",
            "Oman",
            "Jordan",
            "Lebanon",
            "Israel",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Norway",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
        ],
        "enforcement": {
            "mechanism": "Nationally Determined Contributions (NDCs); global stocktake every 5 years",
            "body": "UNFCCC Secretariat",
        },
    },
    {
        "id": "nato",
        "name": "North Atlantic Treaty",
        "subject": "collective_defense",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Canada",
            "Italy",
            "Belgium",
            "Netherlands",
            "Luxembourg",
            "Denmark",
            "Norway",
            "Iceland",
            "Portugal",
            "Greece",
            "Turkey",
            "Spain",
            "Poland",
            "Hungary",
            "Czech Republic",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Slovenia",
            "Slovakia",
            "Romania",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Montenegro",
            "North Macedonia",
            "Finland",
            "Sweden",
        ],
        "enforcement": {
            "mechanism": "Article 5 mutual defense clause; consensus decision-making",
            "body": "North Atlantic Council",
        },
    },
    {
        "id": "npt",
        "name": "Treaty on the Non-Proliferation of Nuclear Weapons (NPT)",
        "subject": "nuclear_nonproliferation",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Russia",
            "China",
            "Germany",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "India",
            "Pakistan",
            "Israel",
            "Iran",
            "Iraq",
            "Saudi Arabia",
            "Turkey",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Romania",
            "Czech Republic",
            "Austria",
            "Greece",
            "Portugal",
            "Ireland",
            "Hungary",
            "Bulgaria",
            "Algeria",
            "Morocco",
            "Tunisia",
            "Libya",
            "Sudan",
            "Ethiopia",
            "Kenya",
            "Tanzania",
            "Uganda",
            "Ghana",
            "Senegal",
            "Cameroon",
            "Colombia",
            "Peru",
            "Chile",
            "Venezuela",
            "Ecuador",
            "Bolivia",
            "Paraguay",
            "Uruguay",
            "Cuba",
            "Afghanistan",
            "Kazakhstan",
            "Uzbekistan",
            "Azerbaijan",
            "Armenia",
            "Georgia",
            "Belarus",
            "Moldova",
            "Slovakia",
            "Slovenia",
            "Croatia",
            "Serbia",
            "Bosnia and Herzegovina",
            "North Macedonia",
            "Albania",
            "Montenegro",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Lebanon",
            "Jordan",
            "Syria",
            "Yemen",
            "Oman",
            "Qatar",
            "Bahrain",
            "Kuwait",
            "United Arab Emirates",
            "Cambodia",
            "Laos",
            "Malaysia",
            "Singapore",
            "Brunei",
            "Sri Lanka",
            "Maldives",
            "Nepal",
            "Bhutan",
            "Bangladesh",
            "Mongolia",
            "New Zealand",
            "Fiji",
        ],
        "enforcement": {
            "mechanism": "IAEA safeguards; UN Security Council referrals for violations",
            "body": "International Atomic Energy Agency",
        },
    },
    {
        "id": "unclos",
        "name": "United Nations Convention on the Law of the Sea (UNCLOS)",
        "subject": "maritime_law",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Saudi Arabia",
            "Iran",
            "Iraq",
            "United Arab Emirates",
            "Qatar",
            "Kuwait",
            "Oman",
            "Jordan",
            "Lebanon",
            "Israel",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Montenegro",
            "North Macedonia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
        ],
        "enforcement": {
            "mechanism": "ITLOS dispute settlement; coastal state enforcement in EEZ",
            "body": "International Tribunal for the Law of the Sea (ITLOS)",
        },
    },
    {
        "id": "cptpp",
        "name": "Comprehensive and Progressive Agreement for Trans-Pacific Partnership (CPTPP)",
        "subject": "trade",
        "parties": [
            "Australia",
            "Brunei",
            "Canada",
            "Chile",
            "Japan",
            "Malaysia",
            "Mexico",
            "New Zealand",
            "Peru",
            "Singapore",
            "Vietnam",
        ],
        "enforcement": {
            "mechanism": "State-to-state dispute settlement; investor-state dispute settlement (ISDS)",
            "body": "CPTPP Commission",
        },
    },
    {
        "id": "usmca",
        "name": "United States-Mexico-Canada Agreement (USMCA)",
        "subject": "trade",
        "parties": ["United States", "Canada", "Mexico"],
        "enforcement": {
            "mechanism": "State-to-state dispute settlement panels; rapid response labor mechanism",
            "body": "USMCA Free Trade Commission",
        },
    },
    {
        "id": "refugee_convention",
        "name": "Convention Relating to the Status of Refugees (1951) and 1967 Protocol",
        "subject": "refugee_protection",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Japan",
            "India",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Indonesia",
            "Thailand",
            "Philippines",
            "South Korea",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Israel",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ecuador",
            "Venezuela",
            "Uruguay",
            "Costa Rica",
            "Panama",
            "Afghanistan",
            "Bangladesh",
            "New Zealand",
            "Serbia",
            "Bosnia and Herzegovina",
            "North Macedonia",
            "Montenegro",
        ],
        "enforcement": {
            "mechanism": "UNHCR supervisory responsibility; non-refoulement principle (Art. 33)",
            "body": "United Nations High Commissioner for Refugees (UNHCR)",
        },
    },
    {
        "id": "chemical_weapons",
        "name": "Chemical Weapons Convention (CWC)",
        "subject": "disarmament",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Russia",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Indonesia",
            "South Korea",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Saudi Arabia",
            "United Arab Emirates",
            "Qatar",
            "Kuwait",
            "Oman",
            "Jordan",
            "Lebanon",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Colombia",
            "Peru",
            "Chile",
            "New Zealand",
            "Singapore",
            "Malaysia",
        ],
        "enforcement": {
            "mechanism": "Challenge inspections; declarations and verification regime",
            "body": "Organisation for the Prohibition of Chemical Weapons (OPCW)",
        },
    },
    {
        "id": "biological_diversity",
        "name": "Convention on Biological Diversity (CBD)",
        "subject": "biodiversity",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Turkey",
            "Pakistan",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "New Zealand",
            "Malaysia",
            "Singapore",
            "Cambodia",
            "Laos",
            "Madagascar",
            "Tanzania",
            "Uganda",
            "Zimbabwe",
            "Namibia",
            "Botswana",
            "Ecuador",
            "Venezuela",
            "Costa Rica",
            "Panama",
            "Paraguay",
            "Uruguay",
            "Bolivia",
            "Papua New Guinea",
            "Fiji",
        ],
        "enforcement": {
            "mechanism": "National Biodiversity Strategies and Action Plans (NBSAPs); Nagoya Protocol on ABS",
            "body": "CBD Secretariat, Conference of the Parties (COP)",
        },
    },
    {
        "id": "rights_of_child",
        "name": "Convention on the Rights of the Child (CRC)",
        "subject": "human_rights",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Saudi Arabia",
            "Iran",
            "Iraq",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "Jordan",
            "Lebanon",
            "Bangladesh",
            "Afghanistan",
            "New Zealand",
            "Uruguay",
            "Ecuador",
            "Costa Rica",
            "Paraguay",
            "Bolivia",
            "Madagascar",
            "Tanzania",
            "Uganda",
            "Zimbabwe",
            "Namibia",
            "Mongolia",
            "Malaysia",
            "Singapore",
        ],
        "enforcement": {
            "mechanism": "State party reports to the Committee on the Rights of the Child; periodic review",
            "body": "UN Committee on the Rights of the Child (CRC Committee)",
        },
    },
    {
        "id": "montreal_protocol",
        "name": "Montreal Protocol on Substances That Deplete the Ozone Layer",
        "subject": "environmental_protection",
        "parties": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Saudi Arabia",
            "Iran",
            "Iraq",
            "United Arab Emirates",
            "Qatar",
            "Kuwait",
            "Oman",
            "Jordan",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "New Zealand",
            "Singapore",
            "Malaysia",
            "Cambodia",
            "Laos",
            "Uruguay",
            "Ecuador",
            "Costa Rica",
            "Paraguay",
            "Bolivia",
            "Papua New Guinea",
            "Fiji",
            "Solomon Islands",
            "Samoa",
        ],
        "enforcement": {
            "mechanism": "Phasedown schedules; Multilateral Fund for implementation assistance",
            "body": "Ozone Secretariat (UNEP)",
        },
    },
    {
        "id": "ctbt",
        "name": "Comprehensive Nuclear-Test-Ban Treaty (CTBT)",
        "subject": "nuclear_disarmament",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Indonesia",
            "Philippines",
            "South Korea",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "New Zealand",
            "Singapore",
            "Malaysia",
            "Colombia",
            "Peru",
            "Chile",
            "Ecuador",
            "Jordan",
            "Lebanon",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Uruguay",
            "Paraguay",
            "Bolivia",
            "Costa Rica",
            "Panama",
            "Bangladesh",
            "Afghanistan",
            "Mongolia",
            "Fiji",
            "Samoa",
            "Solomon Islands",
        ],
        "enforcement": {
            "mechanism": "International Monitoring System (IMS); on-site inspection provisions (upon EIF)",
            "body": "Preparatory Commission for the CTBTO (CTBTO PrepCom)",
        },
    },
    {
        "id": "arms_trade",
        "name": "Arms Trade Treaty (ATT)",
        "subject": "arms_control",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Japan",
            "South Korea",
            "Philippines",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "New Zealand",
            "Senegal",
            "Ghana",
            "Kenya",
            "Colombia",
            "Peru",
            "Chile",
            "Uruguay",
            "Costa Rica",
            "Paraguay",
            "Panama",
            "Jamaica",
            "Trinidad and Tobago",
        ],
        "enforcement": {
            "mechanism": "Annual reporting; export/import licensing controls; diversion risk assessment",
            "body": "ATT Secretariat (Geneva)",
        },
    },
    {
        "id": "tobacco_control",
        "name": "WHO Framework Convention on Tobacco Control (FCTC)",
        "subject": "public_health",
        "parties": [
            "United Kingdom",
            "France",
            "Germany",
            "China",
            "India",
            "Japan",
            "Canada",
            "Australia",
            "Brazil",
            "Argentina",
            "Mexico",
            "South Africa",
            "Nigeria",
            "Egypt",
            "Russia",
            "Indonesia",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Switzerland",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Ukraine",
            "Turkey",
            "Pakistan",
            "Saudi Arabia",
            "Iran",
            "Iraq",
            "Kenya",
            "Ethiopia",
            "Ghana",
            "Senegal",
            "Morocco",
            "Algeria",
            "Tunisia",
            "Colombia",
            "Peru",
            "Chile",
            "Ireland",
            "Portugal",
            "Greece",
            "Austria",
            "Czech Republic",
            "Romania",
            "Hungary",
            "Bulgaria",
            "Albania",
            "Croatia",
            "Slovenia",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Lithuania",
            "New Zealand",
            "Uruguay",
            "Ecuador",
            "Panama",
            "Paraguay",
            "Jordan",
            "Lebanon",
            "Bangladesh",
            "Madagascar",
            "Singapore",
            "Malaysia",
            "Cambodia",
            "Laos",
        ],
        "enforcement": {
            "mechanism": "State party reports; Conference of the Parties review; domestic legislation",
            "body": "WHO FCTC Secretariat",
        },
    },
]


INTERNATIONAL_COURTS: list[dict[str, Any]] = [
    {
        "id": "icj",
        "name": "International Court of Justice",
        "jurisdiction": (
            "Contentious cases between states on treaty interpretation, "
            "territorial disputes, and international law; advisory opinions "
            "to UN bodies. Does not prosecute individuals."
        ),
        "procedures": [
            "Application instituting proceedings",
            "Preliminary objections",
            "Merits phase (written and oral)",
            "Binding judgment (appealable only via revision request)",
        ],
        "notable_cases": [
            "Nicaragua v. United States (1986)",
            "Corfu Channel Case (1949)",
            "South West Africa Cases (1966)",
            "Kosovo Advisory Opinion (2010)",
        ],
    },
    {
        "id": "icc",
        "name": "International Criminal Court",
        "jurisdiction": (
            "Individuals accused of genocide, war crimes, crimes against "
            "humanity, and the crime of aggression. Complementary to "
            "national courts; only acts when states are unwilling or unable."
        ),
        "procedures": [
            "Pre-Trial Chamber authorization",
            "Confirmation of charges",
            "Trial",
            "Appeal and revision",
        ],
        "notable_cases": [
            " Prosecutor v. Omar al-Bashir",
            "Prosecutor v. Thomas Lubanga",
            "Prosecutor v. Uhuru Kenyatta",
            "Uganda situation",
        ],
    },
    {
        "id": "icty",
        "name": "International Criminal Tribunal for the former Yugoslavia",
        "jurisdiction": (
            "Individuals responsible for serious violations of international "
            "humanitarian law committed in the territory of the former "
            "Yugoslavia since 1991. Closed 2017; residual mechanism active."
        ),
        "procedures": [
            "Indictment confirmation",
            "Trial",
            "Appeal",
            "Enforcement of sentences",
        ],
        "notable_cases": [
            "Prosecutor v. Slobodan Milosevic",
            "Prosecutor v. Radovan Karadzic",
            "Prosecutor v. Ratko Mladic",
        ],
    },
    {
        "id": "ictr",
        "name": "International Criminal Tribunal for Rwanda",
        "jurisdiction": (
            "Individuals responsible for genocide and other serious "
            "violations of international humanitarian law committed in "
            "Rwanda or by Rwandan citizens in neighboring states in 1994. "
            "Closed 2015; residual mechanism active."
        ),
        "procedures": [
            "Indictment confirmation",
            "Trial",
            "Appeal",
            "Enforcement of sentences",
        ],
        "notable_cases": [
            "Prosecutor v. Jean-Paul Akayesu",
            "Prosecutor v. Jean Kambanda",
            "Prosecutor v. Theoneste Bagosora",
        ],
    },
    {
        "id": "wto_dsb",
        "name": "World Trade Organization Dispute Settlement Body",
        "jurisdiction": (
            "Trade disputes between WTO member states concerning rights "
            "and obligations under covered agreements (GATT, GATS, TRIPS). "
            "Does not hear criminal matters."
        ),
        "procedures": [
            "Consultations (mandatory)",
            "Panel establishment",
            "Panel report circulation",
            "Appellate Body review",
            "Implementation and retaliation authorization",
        ],
        "notable_cases": [
            "US - Gasoline (1996)",
            "EC - Hormones (1998)",
            "US - Steel Safeguards (2003)",
            "Boeing/Airbus (2021)",
        ],
    },
    {
        "id": "itlos",
        "name": "International Tribunal for the Law of the Sea (ITLOS)",
        "jurisdiction": (
            "Disputes arising from the interpretation or application of "
            "the UN Convention on the Law of the Sea (UNCLOS), including "
            "maritime boundary delimitation, vessel detention, fisheries "
            "access, and environmental protection in the EEZ and high seas. "
            "Established 1996, seated in Hamburg."
        ),
        "procedures": [
            "Application instituting proceedings",
            "Request for provisional measures (if urgent)",
            "Written proceedings (memorial and counter-memorial)",
            "Oral proceedings (public hearings)",
            "Judgment (binding and final)",
        ],
        "notable_cases": [
            "MV Saiga (No. 2) — Saint Vincent v. Guinea (1999)",
            "Arctic Sunrise — Netherlands v. Russia (2014)",
            "Enrica Lexie — Italy v. India (2020)",
            "Request for Advisory Opinion on Climate Change (pending)",
        ],
    },
    {
        "id": "echr",
        "name": "European Court of Human Rights (ECtHR)",
        "jurisdiction": (
            "Alleged violations of the European Convention on Human Rights "
            "(ECHR) by state parties. Individuals and states may bring "
            "applications after exhausting domestic remedies. Judgments "
            "are binding; the Committee of Ministers supervises execution."
        ),
        "procedures": [
            "Application lodged by individual or state",
            "Admissibility decision (exhaustion, 6-month rule, manifestly ill-founded)",
            "Chamber judgment (7 judges)",
            "Grand Chamber referral (exceptional, 17 judges)",
            "Committee of Ministers supervision of execution",
        ],
        "notable_cases": [
            "Soering v. United Kingdom (1989)",
            "Ireland v. United Kingdom (1978)",
            "Ocalan v. Turkey (2005)",
            "Khashiyev and Akayeva v. Russia (2005)",
            "Hirst v. United Kingdom (No. 2) (2005)",
        ],
    },
]


_COURT_JURISDICTION_MAP: dict[str, set[str]] = {
    "icj": {
        "interstate_dispute",
        "boundary_dispute",
        "treaty_interpretation",
        "advisory_opinion",
    },
    "icc": {
        "war_crimes",
        "genocide",
        "crimes_against_humanity",
        "aggression",
    },
    "icty": {
        "war_crimes",
        "genocide",
        "crimes_against_humanity",
    },
    "ictr": {
        "genocide",
        "war_crimes",
        "crimes_against_humanity",
    },
    "wto_dsb": {
        "trade_dispute",
        "tariff_dispute",
        "subsidies_dispute",
        "intellectual_property_dispute",
    },
    "itlos": {
        "maritime_boundary",
        "vessel_detention",
        "fisheries_access",
        "marine_environment",
        "unclos_interpretation",
        "provisional_measures",
    },
    "echr": {
        "human_rights_violation",
        "torture",
        "right_to_life",
        "fair_trial",
        "freedom_of_expression",
        "privacy_violation",
        "discrimination",
        "deprivation_of_liberty",
        "inhuman_treatment",
    },
}


def lookup_conflict(region: str) -> list[dict[str, Any]]:
    """Return conflicts whose ``region`` exactly matches (case-sensitive)."""
    return [c for c in ACTIVE_CONFLICTS if c["region"] == region]


def get_treaty(treaty_id: str) -> dict[str, Any] | None:
    """Return the treaty with the given id (case-sensitive), or None."""
    for t in TREATY_DATABASE:
        if t["id"] == treaty_id:
            return t
    return None


def get_treaty_parties(treaty_id: str) -> list[str]:
    """Return the list of party names for a treaty (empty if unknown)."""
    t = get_treaty(treaty_id)
    if t is None:
        return []
    return list(t["parties"])


def get_treaty_obligations(country: str) -> list[dict[str, Any]]:
    """Return treaty obligations binding on ``country``.

    Each entry is ``{"treaty_id": ..., "subject": ...}``. Only treaties the
    country is a party to are included. Returns ``[]`` for unknown countries.
    """
    out: list[dict[str, Any]] = []
    for t in TREATY_DATABASE:
        if country in t["parties"]:
            out.append({"treaty_id": t["id"], "subject": t["subject"]})
    return out


def get_court_jurisdiction(court_id: str) -> str | None:
    """Return the jurisdiction description string for a court, or None."""
    for c in INTERNATIONAL_COURTS:
        if c["id"] == court_id:
            return c["jurisdiction"]
    return None


def check_court_jurisdiction(court_id: str, case_type: str) -> bool:
    """Return True if ``court_id`` may hear ``case_type``."""
    cases = _COURT_JURISDICTION_MAP.get(court_id)
    if cases is None:
        return False
    return case_type in cases


TREATIES: dict[str, list[dict[str, Any]]] = {t["id"]: [t] for t in TREATY_DATABASE}


def lookup_treaties(treaty_id: str) -> dict[str, Any] | None:
    for t in TREATY_DATABASE:
        if t["id"].lower() == treaty_id.lower():
            result: dict[str, Any] = dict(t)
            result["country"] = treaty_id.upper()
            return result
    return None


__all__ = [
    "ACTIVE_CONFLICTS",
    "CONFLICT_TYPES",
    "INTERNATIONAL_COURTS",
    "TREATIES",
    "TREATY_DATABASE",
    "ConflictType",
    "check_court_jurisdiction",
    "get_court_jurisdiction",
    "get_treaty",
    "get_treaty_obligations",
    "get_treaty_parties",
    "lookup_conflict",
    "lookup_treaties",
]
