"""CapabilityNarrowing — produce child scope from parent's capability lattice.

Phase P2: consumes parent's CapabilityLattice, intersects with the
child's native actions, and emits an OpenBao policy HCL fragment.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from general_ludd.permissions.tool_permissions import (
        CapabilityLattice,
    )

logger = logging.getLogger(__name__)

_ROLE_TO_HCL_VERB: dict[str, str] = {
    "read": "read",
    "write": "create, update",
    "create": "create",
    "overwrite": "update",
    "execute": "sudo",
    "delete": "delete",
}

_ROLE_TO_OPENBAO_PATH: dict[str, str] = {
    "read": "secret/*",
    "write": "secret/*",
    "create": "secret/*",
    "overwrite": "secret/*",
    "execute": "sys/*",
    "delete": "secret/*",
}


@dataclass(frozen=True)
class PolicyFragment:
    """A single HCL path rule within an OpenBao policy.

    Attributes:
        path: The OpenBao path pattern (e.g. ``"secret/*"``).
        capabilities: Verbs permitted on this path (e.g. ``["read"]``).
        constraints: Additional backend-specific constraints (reserved).
    """

    path: str
    capabilities: frozenset[str]
    constraints: dict[str, object] = field(default_factory=dict)


class OpenBaoPolicyRenderer:
    """Renders a set of ToolAction values as an OpenBao HCL policy string.

    Each ToolAction is mapped to an OpenBao path + verbs tuple via the
    built-in ``_ROLE_TO_HCL_VERB`` / ``_ROLE_TO_OPENBAO_PATH`` dictionaries.
    The renderer deduplicates: actions that share the same path are
    merged into a single path entry with a union of verbs.
    """

    @staticmethod
    def render(
        actions: Iterable[object],
        role_name: str = "default",
    ) -> str:
        """Convert a capability action set into an OpenBao HCL policy.

        Args:
            actions: Set of ``ToolAction`` values (or string action names).
            role_name: The policy name (used in the HCL ``path`` block name).

        Returns:
            An HCL policy fragment string suitable for
            ``hvac.api.secrets_engines.AppRole.create_role()``.
        """
        if not actions:
            return ""

        action_strs = sorted(
            str(a.value if hasattr(a, "value") else a) for a in actions
        )

        path_verbs: dict[str, set[str]] = {}
        for a in action_strs:
            path = _ROLE_TO_OPENBAO_PATH.get(a, "secret/*")
            verbs = _ROLE_TO_HCL_VERB.get(a, a)
            if path not in path_verbs:
                path_verbs[path] = set()
            for verb in verbs.split(", "):
                path_verbs[path].add(verb)

        lines: list[str] = []
        lines.append(f'# Policy for role "{role_name}" — generated by CapabilityNarrowing')
        for bao_path, verb_set in sorted(path_verbs.items()):
            verb_list = ", ".join(sorted(verb_set))
            lines.append(f'path "{bao_path}" {{')
            lines.append(f"  capabilities = [\"{verb_list}\"]")
            lines.append("}")

        return "\n".join(lines) + "\n"


class CapabilityNarrowing:
    """Intersects parent capability lattice to produce child scope.

    Consumes the parent agent's :class:`CapabilityLattice` and narrows a
    child's requested actions to never exceed what the parent holds.
    Provides anti-escalation validation and OpenBao policy rendering.

    Per the spec (docs/specs/FEATURE_STS_TOKENS.md §2):
        child_actions = parent_actions ∩ child_native_actions
    """

    def __init__(self, parent_lattice: CapabilityLattice) -> None:
        self._parent_lattice = parent_lattice

    @property
    def parent_lattice(self) -> CapabilityLattice:
        return self._parent_lattice

    def narrow(
        self,
        child_actions: set[object],
        parent_role: str = "admin",
    ) -> set[str]:
        """Produce the child's narrowed action set.

        Computes ``child_actions ∩ parent_all_actions`` so the result is
        always a subset of what the parent role holds.

        Args:
            child_actions: The actions the child requests (``set[ToolAction]``
                or ``set[str]``).
            parent_role: The role to evaluate in the parent's lattice.

        Returns:
            Intersection of child requests and parent's all_actions for
            the given role.
        """
        parent_all = self._parent_lattice.all_actions(parent_role)
        child_action_strs = {
            str(a.value if hasattr(a, "value") else a) for a in child_actions
        }

        narrowed = child_action_strs & parent_all
        if narrowed != child_action_strs:
            dropped = child_action_strs - narrowed
            logger.debug(
                "CapabilityNarrowing dropped actions not in parent lattice: %s",
                sorted(dropped),
            )
        return narrowed

    @staticmethod
    def validate_narrowing(
        parent_actions: set[object],
        child_actions: set[object],
    ) -> bool:
        """Anti-escalation check: child actions must be a subset of parent actions.

        Returns True if every child action is present in parent actions (child
        does not exceed parent). Returns False if child requests any action
        absent from parent — this is an escalation attempt.
        """
        parent_set: set[str] = {
            str(a.value if hasattr(a, "value") else a) for a in parent_actions
        }
        child_set: set[str] = {
            str(a.value if hasattr(a, "value") else a) for a in child_actions
        }
        return child_set.issubset(parent_set)

    def to_openbao_policy(
        self,
        actions: set[object],
        role_name: str = "subagent",
    ) -> str:
        """Convert narrowed actions to an OpenBao HCL policy fragment.

        Delegates to :class:`OpenBaoPolicyRenderer` after narrowing so the
        emitted policy only covers actions the parent lattice grants.

        Args:
            actions: The child's requested actions (pre-narrowing; will be
                narrowed via :meth:`narrow` internally).
            role_name: Policy name for the HCL header comment.

        Returns:
            HCL policy fragment string.
        """
        narrowed_set: set[str]
        if self._parent_lattice.chain:
            narrowed_set = self.narrow(actions)
        else:
            narrowed_set = {str(a.value if hasattr(a, "value") else a) for a in actions}
        return OpenBaoPolicyRenderer.render(narrowed_set, role_name=role_name)


__all__ = [
    "CapabilityNarrowing",
    "OpenBaoPolicyRenderer",
    "PolicyFragment",
]
