---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Include windows_security"
      ansible.builtin.include_role:
        name: "general_ludd.os_expert.windows_security"
