"""Minimal typing contract for the quickjs-ng context used by Gludd."""

class Context:
    """Constrained JavaScript context exposed by quickjs-ng."""

    def set_memory_limit(self, limit: int) -> None: ...
    def set_time_limit(self, limit: float) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def eval(self, source: str) -> object: ...
