variable "deployment_name" {
  description = "Unique Azure Container App deployment name generated by gludd."
  type        = string
}

variable "region" {
  description = "Azure region selected by the read-only deployment preflight."
  type        = string
}

variable "container_image" {
  description = "Digest-pinned vLLM container image deployed to Azure Container Apps."
  type        = string
}

variable "model_name" {
  description = "Hugging Face model identifier served by vLLM."
  type        = string
}

variable "gpu_type" {
  description = "Azure Container Apps GPU workload-profile type."
  type        = string
}

variable "gpu_count" {
  description = "Number of GPUs exposed by the selected workload profile."
  type        = number
}

variable "allowed_cidr" {
  description = "Only CIDR permitted to reach the inference endpoint."
  type        = string
}

variable "max_cost_usd" {
  description = "Maximum intended deployment spend."
  type        = number
}

variable "timeout_minutes" {
  description = "Bounded deployment lifetime before Gludd-owned teardown."
  type        = number
}

variable "use_spot" {
  description = "Spot capacity is not supported for Azure Container Apps; retained as a false-only interface default."
  type        = bool
  default     = false

  validation {
    condition     = !var.use_spot
    error_message = "use_spot must remain false because Azure Container Apps GPU profiles do not support spot capacity."
  }
}

variable "vllm_context_length" {
  description = "Maximum context length supplied to the vLLM server."
  type        = number
}

variable "vllm_max_num_seqs" {
  description = "Maximum concurrent sequences accepted by vLLM."
  type        = number
}

variable "vllm_gpu_memory_utilization" {
  description = "Fraction of GPU memory reserved for vLLM."
  type        = number
}

variable "vllm_enforce_eager" {
  description = "Disable CUDA graph execution when true."
  type        = bool
}

variable "vllm_enable_prefix_caching" {
  description = "Enable vLLM automatic prefix caching."
  type        = bool
}

variable "vllm_enable_chunked_prefill" {
  description = "Enable vLLM chunked prefill scheduling."
  type        = bool
}

variable "vllm_kv_cache_dtype" {
  description = "Data type used by the vLLM key-value cache."
  type        = string
}

variable "vllm_quantization" {
  description = "Optional vLLM quantization method."
  type        = string
}
