---
- name: Restart native searxng
  general_ludd.travel.searxng_instance:
    state: restarted
    namespace: "{{ searxng_namespace }}"
    settings_path: "{{ searxng_settings_path }}"
  when: searxng_enabled | bool
  listen: restart searxng
