---
git_release_artifact_build_enabled: false
git_release_artifact_build_request:
  path: "{{ playbook_dir }}"
git_release_artifact_build_result_fact: git_release_artifact_build_result
git_release_artifact_build_output_path: ""
