---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Include macos_security"
      ansible.builtin.include_role:
        name: "general_ludd.os_expert.macos_security"
      vars:
        enable_git_push: false
