"""Remove only Terraform tfvars files generated by the all-stacks test."""

from __future__ import annotations

import argparse
from pathlib import Path

GENERATED_MARKER = "# Auto-generated by test_terraform_all_stacks_valid.py"
GENERATED_NAME = "terraform.auto.tfvars"


def clean_generated_tfvars(stack_dir: Path) -> bool:
    """Delete the generated tfvars file while preserving operator-authored files."""

    if not stack_dir.is_dir():
        raise ValueError(f"stack directory does not exist: {stack_dir}")
    candidate = stack_dir / GENERATED_NAME
    if not candidate.exists() and not candidate.is_symlink():
        return False
    try:
        first_line = candidate.read_text(encoding="utf-8").splitlines()[0]
    except (IndexError, OSError, UnicodeError):
        return False
    if first_line != GENERATED_MARKER:
        return False
    candidate.unlink()
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("stack_dir", type=Path)
    args = parser.parse_args()
    try:
        removed = int(clean_generated_tfvars(args.stack_dir))
    except ValueError as exc:
        print(f"terraform-test-artifacts error={exc}")
        return 2
    print(f"terraform-test-artifacts removed={removed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
