#!/usr/bin/env python3
"""Functional test facade for the OpenCode plugin hook runtime suite.

The implementations live in :mod:`scripts.hook_runtime`; explicit aliases keep
the historical ``scripts/test_hook_runtime.py::<case>`` node IDs and CLI stable.
"""

from __future__ import annotations

import os
import subprocess
import sys

import pytest
from hook_runtime import facade_exports as _exports

ROOT = _exports.ROOT
_OPENCODE_DIR = _exports._OPENCODE_DIR
PLUGIN_DIR = _exports.PLUGIN_DIR
LIB_DIR = _exports.LIB_DIR
_PLUGINS_PRESENT = _exports._PLUGINS_PRESENT
_GLOBAL_RUNTIME_STATE_NAMES = _exports._GLOBAL_RUNTIME_STATE_NAMES
_LEGACY_WORKSPACE_TEMP_NAMES = _exports._LEGACY_WORKSPACE_TEMP_NAMES
WATCHDOG_PATH = _exports.WATCHDOG_PATH

_runtime_state_root = _exports._runtime_state_root
_runtime_state_path = _exports._runtime_state_path
_dirty_test_path = _exports._dirty_test_path
_remove_legacy_workspace_artifacts = _exports._remove_legacy_workspace_artifacts
_cleanup_legacy_workspace_artifacts = _exports._cleanup_legacy_workspace_artifacts
_run_ts = _exports._run_ts
_factory_plugin_code = _exports._factory_plugin_code
_pluginapi_code = _exports._pluginapi_code
_clean_state_files = _exports._clean_state_files
_with_open_work = _exports._with_open_work
_hermetic_project_root = _exports._hermetic_project_root
_fresh_session_state = _exports._fresh_session_state
_session_start_dispatch_then_bash = _exports._session_start_dispatch_then_bash
_enforce_make_bash_test = _exports._enforce_make_bash_test

pytestmark = pytest.mark.skipif(
    not _PLUGINS_PRESENT,
    reason=f"no plugins found under {PLUGIN_DIR} (set OPENCODE_DIR=... to test a different location)",
)

test_runtime_state_root_honors_isolated_directory = _exports.test_runtime_state_root_honors_isolated_directory
test_runtime_state_path_redirects_only_known_global_state = (
    _exports.test_runtime_state_path_redirects_only_known_global_state
)
test_run_ts_returns_none_for_empty_stdout = _exports.test_run_ts_returns_none_for_empty_stdout
test_run_ts_ignores_non_json_diagnostics = _exports.test_run_ts_ignores_non_json_diagnostics
test_run_ts_namespaces_streak_state_per_invocation = _exports.test_run_ts_namespaces_streak_state_per_invocation
test_shared_explicit_non_subagent_ignores_stale_pid_marker = (
    _exports.test_shared_explicit_non_subagent_ignores_stale_pid_marker
)
test_clean_tree_get_git_status = _exports.test_clean_tree_get_git_status
test_clean_tree_is_dirty_in_real_repo = _exports.test_clean_tree_is_dirty_in_real_repo
test_clean_tree_count_dirty_files_zero = _exports.test_clean_tree_count_dirty_files_zero
test_clean_tree_count_dirty_files_nonzero = _exports.test_clean_tree_count_dirty_files_nonzero
test_clean_tree_build_deny_message = _exports.test_clean_tree_build_deny_message
test_clean_tree_dispatch_tools_defined = _exports.test_clean_tree_dispatch_tools_defined
test_clean_tree_hook_dispatch_with_dirty_tree = _exports.test_clean_tree_hook_dispatch_with_dirty_tree
test_clean_tree_hook_clean_tree_allows_dispatch = _exports.test_clean_tree_hook_clean_tree_allows_dispatch
test_clean_tree_env_disable = _exports.test_clean_tree_env_disable
test_clean_tree_subagent_skip = _exports.test_clean_tree_subagent_skip
test_enhancement_enhancement_keywords_classify_correctly = (
    _exports.test_enhancement_enhancement_keywords_classify_correctly
)
test_enhancement_fix_keywords_classify_correctly = _exports.test_enhancement_fix_keywords_classify_correctly
test_enhancement_unknown_defaults_to_fix = _exports.test_enhancement_unknown_defaults_to_fix
test_enhancement_wave_80pct_fixes_triggers_text_complete_block = (
    _exports.test_enhancement_wave_80pct_fixes_triggers_text_complete_block
)
test_enhancement_wave_50pct_allowed = _exports.test_enhancement_wave_50pct_allowed
test_enhancement_env_disable = _exports.test_enhancement_env_disable
test_enhancement_subagent_skip = _exports.test_enhancement_subagent_skip
test_enhancement_fix_ratio_ok = _exports.test_enhancement_fix_ratio_ok
test_enhancement_fix_ratio_violation_blocked = _exports.test_enhancement_fix_ratio_violation_blocked
test_enhancement_fix_ratio_text_blocked = _exports.test_enhancement_fix_ratio_text_blocked
test_enhancement_block_env_disabled = _exports.test_enhancement_block_env_disabled
test_enhancement_wave_too_small = _exports.test_enhancement_wave_too_small
test_delegate_streak_zero_allowed = _exports.test_delegate_streak_zero_allowed
test_delegate_streak_at_threshold_denied = _exports.test_delegate_streak_at_threshold_denied
test_delegate_read_tool_not_counted = _exports.test_delegate_read_tool_not_counted
test_delegate_env_disable = _exports.test_delegate_env_disable
test_deadline_task_within_timeout_allowed = _exports.test_deadline_task_within_timeout_allowed
test_deadline_task_over_timeout_blocked = _exports.test_deadline_task_over_timeout_blocked
test_deadline_env_disable = _exports.test_deadline_env_disable
test_deadline_block_env_disabled = _exports.test_deadline_block_env_disabled
test_deadline_subagent_guard = _exports.test_deadline_subagent_guard
test_deadline_corrupt_state_fail_open = _exports.test_deadline_corrupt_state_fail_open
test_deadline_no_state_file_fail_open = _exports.test_deadline_no_state_file_fail_open
test_floor_dispatch_resets_streak = _exports.test_floor_dispatch_resets_streak
test_floor_streak_zero_non_dispatch_allowed = _exports.test_floor_streak_zero_non_dispatch_allowed
test_floor_streak_max_plus_one_denied = _exports.test_floor_streak_max_plus_one_denied
test_floor_subagent_env_skip = _exports.test_floor_subagent_env_skip
test_floor_corrupt_state_fail_open = _exports.test_floor_corrupt_state_fail_open
test_floor_read_tool_not_blocked = _exports.test_floor_read_tool_not_blocked
test_floor_text_complete_blocks_on_zero_dispatches = _exports.test_floor_text_complete_blocks_on_zero_dispatches
test_floor_message_shape_one_dispatch_denied = _exports.test_floor_message_shape_one_dispatch_denied
test_floor_result_grace_denies_non_dispatch = _exports.test_floor_result_grace_denies_non_dispatch
test_floor_text_complete_subagent_skip = _exports.test_floor_text_complete_subagent_skip
test_floor_disengage_allows_after_streak_breach = _exports.test_floor_disengage_allows_after_streak_breach
test_multitask_text_complete_blocks_thin_wave = _exports.test_multitask_text_complete_blocks_thin_wave
test_multitask_enough_dispatches = _exports.test_multitask_enough_dispatches
test_multitask_single_dispatch_blocked = _exports.test_multitask_single_dispatch_blocked
test_multitask_zero_dispatch_text_blocked = _exports.test_multitask_zero_dispatch_text_blocked
test_multitask_subagent_guard = _exports.test_multitask_subagent_guard
test_multitask_env_disabled = _exports.test_multitask_env_disabled
test_multitask_configured_minimum_hard_block = _exports.test_multitask_configured_minimum_hard_block
test_multitask_dispatch_ceiling_blocked = _exports.test_multitask_dispatch_ceiling_blocked
test_multitask_consecutive_non_dispatch_blocked = _exports.test_multitask_consecutive_non_dispatch_blocked
test_multitask_corrupt_state_fail_open = _exports.test_multitask_corrupt_state_fail_open
test_multitask_zero_floor_keeps_inline_mutation_available = (
    _exports.test_multitask_zero_floor_keeps_inline_mutation_available
)
test_multitask_text_only_response_next_tool_blocked = _exports.test_multitask_text_only_response_next_tool_blocked
test_multitask_zero_dispatch_text_blocked_after_prior_dispatch = (
    _exports.test_multitask_zero_dispatch_text_blocked_after_prior_dispatch
)
test_stop_pending_work_text_blanked = _exports.test_stop_pending_work_text_blanked
test_stop_no_pending_work = _exports.test_stop_no_pending_work
test_stop_env_disabled = _exports.test_stop_env_disabled
test_stop_corrupt_state = _exports.test_stop_corrupt_state
test_stop_block_persists_across_turns = _exports.test_stop_block_persists_across_turns
test_stop_block_cleared_by_dispatch = _exports.test_stop_block_cleared_by_dispatch
test_stop_no_pending_work_allows = _exports.test_stop_no_pending_work_allows
test_stop_subagent_block_guard = _exports.test_stop_subagent_block_guard
test_stop_task_result_passes_through_gate_red = _exports.test_stop_task_result_passes_through_gate_red
test_stop_permission_seeking_want_me_to_blocked = _exports.test_stop_permission_seeking_want_me_to_blocked
test_stop_permission_seeking_should_i_blocked = _exports.test_stop_permission_seeking_should_i_blocked
test_stop_permission_seeking_export_matches = _exports.test_stop_permission_seeking_export_matches
test_stop_status_summary_blocked_despite_evidence = _exports.test_stop_status_summary_blocked_despite_evidence
test_stop_status_summary_export_matches = _exports.test_stop_status_summary_export_matches
test_clean_tree_dispatch_allowed = _exports.test_clean_tree_dispatch_allowed
test_clean_tree_dirty_dispatch_blocked = _exports.test_clean_tree_dirty_dispatch_blocked
test_clean_tree_env_disabled = _exports.test_clean_tree_env_disabled
test_clean_tree_subagent_guard = _exports.test_clean_tree_subagent_guard
test_clean_tree_isTreeDirty_empty_string = _exports.test_clean_tree_isTreeDirty_empty_string
test_clean_tree_countDirtyFiles_edge_cases = _exports.test_clean_tree_countDirtyFiles_edge_cases
test_clean_tree_countDirtyFiles_single_line = _exports.test_clean_tree_countDirtyFiles_single_line
test_clean_tree_non_dispatch_tool_not_blocked = _exports.test_clean_tree_non_dispatch_tool_not_blocked
test_clean_tree_buildDenyMessage_edge_cases = _exports.test_clean_tree_buildDenyMessage_edge_cases
test_clean_tree_getGitStatus_real_repo_returns_string = _exports.test_clean_tree_getGitStatus_real_repo_returns_string
test_clean_tree_hook_throws_on_execsync_failure = _exports.test_clean_tree_hook_throws_on_execsync_failure
test_verified_claim_with_evidence = _exports.test_verified_claim_with_evidence
test_verified_claim_no_evidence_blocked = _exports.test_verified_claim_no_evidence_blocked
test_verified_claims_commit_unverified_msg_blocked = _exports.test_verified_claims_commit_unverified_msg_blocked
test_verified_claims_commit_verified_msg_allowed = _exports.test_verified_claims_commit_verified_msg_allowed
test_verified_claims_subagent_skip = _exports.test_verified_claims_subagent_skip
test_no_suppression_plain_comment = _exports.test_no_suppression_plain_comment
test_no_suppression_noqa_blocked = _exports.test_no_suppression_noqa_blocked
test_no_suppression_type_ignore_blocked = _exports.test_no_suppression_type_ignore_blocked
test_no_suppression_allowlisted_file = _exports.test_no_suppression_allowlisted_file
test_no_wait_sleep_blocked = _exports.test_no_wait_sleep_blocked
test_no_wait_gate_tail_blocked = _exports.test_no_wait_gate_tail_blocked
test_no_wait_subagent_bypass = _exports.test_no_wait_subagent_bypass
test_no_wait_env_disabled = _exports.test_no_wait_env_disabled
test_no_wait_corrupt_input_fail_open = _exports.test_no_wait_corrupt_input_fail_open
test_deletion_under_threshold_allowed = _exports.test_deletion_under_threshold_allowed
test_deletion_over_threshold_blocked = _exports.test_deletion_over_threshold_blocked
test_deletion_subagent_guard = _exports.test_deletion_subagent_guard
test_deletion_env_disabled = _exports.test_deletion_env_disabled
test_session_start_fresh_no_reads_mutation_denied = _exports.test_session_start_fresh_no_reads_mutation_denied
test_session_start_read_tool_always_allowed = _exports.test_session_start_read_tool_always_allowed
test_session_start_subagent_guard = _exports.test_session_start_subagent_guard
test_session_start_env_disable = _exports.test_session_start_env_disable
test_session_start_corrupt_state_fail_open = _exports.test_session_start_corrupt_state_fail_open
test_session_start_read_task_file_sets_readsDone = _exports.test_session_start_read_task_file_sets_readsDone
test_session_start_read_bugs_md_sets_readsDone = _exports.test_session_start_read_bugs_md_sets_readsDone
test_session_start_read_non_task_file_does_not_set_readsDone = (
    _exports.test_session_start_read_non_task_file_does_not_set_readsDone
)
test_session_start_dispatch_increment_default_adaptive = _exports.test_session_start_dispatch_increment_default_adaptive
test_session_start_explicit_minimum_denies_under_dispatch = (
    _exports.test_session_start_explicit_minimum_denies_under_dispatch
)
test_make_allows_make_target = _exports.test_make_allows_make_target
test_make_denies_cd_command = _exports.test_make_denies_cd_command
test_make_denies_python = _exports.test_make_denies_python
test_make_denies_pip = _exports.test_make_denies_pip
test_make_denies_git = _exports.test_make_denies_git
test_make_denies_metachar_pipe = _exports.test_make_denies_metachar_pipe
test_make_denies_metachar_semicolon = _exports.test_make_denies_metachar_semicolon
test_make_denies_metachar_and = _exports.test_make_denies_metachar_and
test_make_denies_metachar_dollar = _exports.test_make_denies_metachar_dollar
test_make_denies_redirect = _exports.test_make_denies_redirect
test_make_subagent_guard = _exports.test_make_subagent_guard
test_make_disengage_escape = _exports.test_make_disengage_escape
test_make_allows_make_lint = _exports.test_make_allows_make_lint
test_make_denies_python3 = _exports.test_make_denies_python3
test_make_denies_gh = _exports.test_make_denies_gh
test_make_denies_cat = _exports.test_make_denies_cat
test_make_denies_git_status = _exports.test_make_denies_git_status
test_make_denies_pipe_in_make_args = _exports.test_make_denies_pipe_in_make_args
test_make_denies_and_in_make_args = _exports.test_make_denies_and_in_make_args
test_additive_task_runtime_hook_invocation = _exports.test_additive_task_runtime_hook_invocation
test_anti_essay_runtime_hook_invocation = _exports.test_anti_essay_runtime_hook_invocation
test_anti_essay_blocks_explanation_status_phrase_with_pending_work = (
    _exports.test_anti_essay_blocks_explanation_status_phrase_with_pending_work
)
test_audit_runtime_hook_invocation = _exports.test_audit_runtime_hook_invocation
test_batch_push_runtime_hook_invocation = _exports.test_batch_push_runtime_hook_invocation
test_branch_discipline_runtime_hook_invocation = _exports.test_branch_discipline_runtime_hook_invocation
test_context_runtime_hook_invocation = _exports.test_context_runtime_hook_invocation
test_deliverable_runtime_hook_invocation = _exports.test_deliverable_runtime_hook_invocation
test_depth_runtime_hook_invocation = _exports.test_depth_runtime_hook_invocation
test_directives_runtime_hook_invocation = _exports.test_directives_runtime_hook_invocation
test_floor_v2_runtime_hook_invocation = _exports.test_floor_v2_runtime_hook_invocation
test_no_ci_poll_runtime_hook_invocation = _exports.test_no_ci_poll_runtime_hook_invocation
test_no_suppressions_runtime_hook_invocation = _exports.test_no_suppressions_runtime_hook_invocation
test_objective_runtime_hook_invocation = _exports.test_objective_runtime_hook_invocation
test_pipeline_kickoff_runtime_hook_invocation = _exports.test_pipeline_kickoff_runtime_hook_invocation
test_release_deadline_runtime_hook_invocation = _exports.test_release_deadline_runtime_hook_invocation
test_task_tracking_runtime_hook_invocation = _exports.test_task_tracking_runtime_hook_invocation
test_tdd_runtime_hook_invocation = _exports.test_tdd_runtime_hook_invocation
test_test_integrity_runtime_hook_invocation = _exports.test_test_integrity_runtime_hook_invocation
test_worktree_runtime_hook_invocation = _exports.test_worktree_runtime_hook_invocation
test_watchdog_event_hook_runtime_invocation = _exports.test_watchdog_event_hook_runtime_invocation
test_watchdog_plugin_loads_report_alive = _exports.test_watchdog_plugin_loads_report_alive
test_watchdog_plugin_loads_no_error = _exports.test_watchdog_plugin_loads_no_error
test_watchdog_plugin_subagent_context = _exports.test_watchdog_plugin_subagent_context
test_watchdog_plugin_env_disabled = _exports.test_watchdog_plugin_env_disabled
test_watchdog_plugin_loads_with_corrupt_pid_file = _exports.test_watchdog_plugin_loads_with_corrupt_pid_file
test_commit_lock_allowed_no_lock = _exports.test_commit_lock_allowed_no_lock
test_commit_lock_fresh_lock_denies = _exports.test_commit_lock_fresh_lock_denies
test_commit_lock_stale_break_allows = _exports.test_commit_lock_stale_break_allows
test_commit_lock_non_commit_allowed = _exports.test_commit_lock_non_commit_allowed
test_commit_lock_subagent_guard = _exports.test_commit_lock_subagent_guard
test_commit_lock_env_disable = _exports.test_commit_lock_env_disable
test_commit_lock_after_releases_lock = _exports.test_commit_lock_after_releases_lock
test_commit_lock_is_commit_command = _exports.test_commit_lock_is_commit_command

# Compatibility ports: tests and operators historically monkeypatch these
# module objects through the facade; runner.py observes the same shared objects.
_COMPAT_MODULE_PORTS = (os, subprocess)


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v", *sys.argv[1:]]))
