"""AI/ML expert service package.

Implements capabilities from docs/specs/FEATURE_AI_ML_EXPERT.md:

  - AIML-001 Expert router  -> :class:`ExpertRouter`
  - AIML-002 Research discovery -> :class:`ResearchDiscovery`
  - AIML-003 Evidence store  -> :class:`EvidenceStore`
  - AIML-007 Reasoning/answer -> :class:`ReasoningEngine`, :func:`answer_question`
  - AIML-018 Tool discovery   -> :func:`discover_tools`
  - Phase A registries        -> :class:`Registry`, :class:`RegistryRecord`,
    :class:`Source`, :class:`Dataset`, :class:`Model`, :class:`Adapter`,
    :class:`Simulator`, :class:`EvaluationSuite`, :class:`Deployment`
  - Phase B-D domains         -> accelerators, adaptation, datasets,
    distillation, evaluation, policy, promotion, retrieval, speech,
    vision, world models

The ansible collection under
``collections/ansible_collections/general_ludd/ai_ml/`` wraps these typed
entry points; it never duplicates prompts or knowledge (spec §3.1).
"""

from __future__ import annotations

from general_ludd.ai_ml.accelerators import (
    AcceleratorKind,
    AcceleratorPlanner,
    CheckpointRef,
    DryRunResult,
    ExecutionPlan,
    HardwareDescriptor,
    ResumeResult,
    TeardownProof,
)
from general_ludd.ai_ml.adaptation import (
    AdapterManifest,
    AdapterMethod,
    CheckpointStrategy,
    Quantization,
    SafeStopResult,
    TrainingPlan,
    TrainingStopReason,
    plan_adaptation,
    safe_stop,
    validate_adapter,
)
from general_ludd.ai_ml.datasets import (
    DataCard,
    DatasetManifest,
    DatasetSchema,
    FindingKind,
    FormatId,
    FormatSelection,
    FormatSelector,
    FormatTradeoff,
    Severity,
    ShardDigest,
    ValidationFinding,
    select_format,
    validate_dataset,
)
from general_ludd.ai_ml.distillation import (
    DataFilterRule,
    DistillationPlan,
    DistillationType,
    FilterAction,
    RetentionThreshold,
    StudentValidation,
    plan_distillation,
    validate_student,
)
from general_ludd.ai_ml.evaluation import (
    BenchmarkResult,
    EvaluationHarness,
    MetricKind,
    MetricScore,
    PromotionDecision,
    RegressionVerdict,
)
from general_ludd.ai_ml.evidence import (
    EVIDENCE_POLICY_RULESET_SHA256,
    EvidenceStore,
)
from general_ludd.ai_ml.policy import (
    PolicyEngine,
    PolicyResult,
)
from general_ludd.ai_ml.promotion import (
    AliasSwap,
    CanaryBudgets,
    CanaryMetrics,
    CanaryVerdict,
    PromotionGate,
    PromotionPhase,
    RollbackResult,
)
from general_ludd.ai_ml.reasoning import (
    IndependentCheck,
    IndependentCheckKind,
    NumericalAnswer,
    ReasoningEngine,
    ReasoningPhase,
    ReasoningResult,
    StepArtifact,
)
from general_ludd.ai_ml.registries import (
    Adapter,
    Dataset,
    Deployment,
    EvaluationSuite,
    Model,
    Registry,
    RegistryRecord,
    Simulator,
    Source,
    ValidationState,
)
from general_ludd.ai_ml.research import (
    AuthorityScore,
    QueryPortfolio,
    ResearchDiscovery,
    RetrievedItem,
    SourceConnectorKind,
)
from general_ludd.ai_ml.retrieval import (
    RetrievalMetrics,
    RetrievalResult,
    RetrievalService,
    RetrievedPassage,
)
from general_ludd.ai_ml.router import (
    ExpertRouter,
    answer_question,
    discover_tools,
)
from general_ludd.ai_ml.schemas import (
    ArtifactInput,
    ArtifactOutput,
    Citation,
    Constraints,
    CostRecord,
    DataClassification,
    ErrorRecord,
    EvidenceArtifact,
    ExpertRequest,
    ExpertResult,
    ExpertTask,
    PolicyDecision,
    ResultStatus,
    RouterDecision,
    ToolCandidate,
    ToolDecisionRecord,
    Uncertainty,
    Verification,
    VerificationStatus,
)
from general_ludd.ai_ml.simulators import (
    Determinism,
    ResourceLimits,
    SandboxProfile,
    SimulationResult,
    SimulatorAdapter,
    run_simulation,
)
from general_ludd.ai_ml.speech import (
    ASRRequest,
    ASRResult,
    ASRSegment,
    ConsentDecision,
    NonSpeechEvent,
    PrivacyClass,
    TimestampGranularity,
    TTSRequest,
    TTSResult,
    VoiceConsent,
    check_voice_consent,
    compute_audio_retention,
    is_custom_voice,
    word_error_rate,
)
from general_ludd.ai_ml.vision import (
    BoundingBox,
    Classification,
    ContentDomain,
    Detection,
    ImageEditRecord,
    ImageOperation,
    ImageOperationType,
    Segmentation,
    VisionRequest,
    VisionResult,
    VisionTask,
)
from general_ludd.ai_ml.world_models import (
    ConstraintSpec,
    ConstraintViolation,
    HorizonError,
    HorizonMetrics,
    RolloutEvaluation,
    RolloutUncertainty,
    WorldModelEnvironment,
    WorldModelKind,
    evaluate_rollout,
)

__all__ = [
    "EVIDENCE_POLICY_RULESET_SHA256",
    "ASRRequest",
    "ASRResult",
    "ASRSegment",
    "AcceleratorKind",
    "AcceleratorPlanner",
    "Adapter",
    "AdapterManifest",
    "AdapterMethod",
    "AliasSwap",
    "ArtifactInput",
    "ArtifactOutput",
    "AuthorityScore",
    "BenchmarkResult",
    "BoundingBox",
    "CanaryBudgets",
    "CanaryMetrics",
    "CanaryVerdict",
    "CheckpointRef",
    "CheckpointStrategy",
    "Citation",
    "Classification",
    "ConsentDecision",
    "ConstraintSpec",
    "ConstraintViolation",
    "Constraints",
    "ContentDomain",
    "CostRecord",
    "DataCard",
    "DataClassification",
    "DataFilterRule",
    "Dataset",
    "DatasetManifest",
    "DatasetSchema",
    "Deployment",
    "Detection",
    "Determinism",
    "DistillationPlan",
    "DistillationType",
    "DryRunResult",
    "ErrorRecord",
    "EvaluationHarness",
    "EvaluationSuite",
    "EvidenceArtifact",
    "EvidenceStore",
    "ExecutionPlan",
    "ExpertRequest",
    "ExpertResult",
    "ExpertRouter",
    "ExpertTask",
    "FilterAction",
    "FindingKind",
    "FormatId",
    "FormatSelection",
    "FormatSelector",
    "FormatTradeoff",
    "HardwareDescriptor",
    "HorizonError",
    "HorizonMetrics",
    "ImageEditRecord",
    "ImageOperation",
    "ImageOperationType",
    "IndependentCheck",
    "IndependentCheckKind",
    "MetricKind",
    "MetricScore",
    "Model",
    "NonSpeechEvent",
    "NumericalAnswer",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyResult",
    "PrivacyClass",
    "PromotionDecision",
    "PromotionGate",
    "PromotionPhase",
    "Quantization",
    "QueryPortfolio",
    "ReasoningEngine",
    "ReasoningPhase",
    "ReasoningResult",
    "Registry",
    "RegistryRecord",
    "RegressionVerdict",
    "ResearchDiscovery",
    "ResourceLimits",
    "ResultStatus",
    "ResumeResult",
    "RetentionThreshold",
    "RetrievalMetrics",
    "RetrievalResult",
    "RetrievalService",
    "RetrievedItem",
    "RetrievedPassage",
    "RollbackResult",
    "RolloutEvaluation",
    "RolloutUncertainty",
    "RouterDecision",
    "SafeStopResult",
    "SandboxProfile",
    "Segmentation",
    "Severity",
    "ShardDigest",
    "SimulationResult",
    "Simulator",
    "SimulatorAdapter",
    "Source",
    "SourceConnectorKind",
    "StepArtifact",
    "StudentValidation",
    "TTSRequest",
    "TTSResult",
    "TeardownProof",
    "TimestampGranularity",
    "ToolCandidate",
    "ToolDecisionRecord",
    "TrainingPlan",
    "TrainingStopReason",
    "Uncertainty",
    "ValidationFinding",
    "ValidationState",
    "Verification",
    "VerificationStatus",
    "VisionRequest",
    "VisionResult",
    "VisionTask",
    "VoiceConsent",
    "WorldModelEnvironment",
    "WorldModelKind",
    "answer_question",
    "check_voice_consent",
    "compute_audio_retention",
    "discover_tools",
    "evaluate_rollout",
    "is_custom_voice",
    "plan_adaptation",
    "plan_distillation",
    "run_simulation",
    "safe_stop",
    "select_format",
    "validate_adapter",
    "validate_dataset",
    "validate_student",
    "word_error_rate",
]
