# --- Terraform: shared provider plugin cache (one download per provider) -----
# Resolves docs/design/TERRAFORM_INFRA_STRUCTURE.md §10 #3: third-party
# providers (aws, google, azurerm, kubernetes, vsphere, runpod) used to be
# re-downloaded once per stack (14 stack-provider downloads for 6 providers).
# TF_PLUGIN_CACHE_DIR makes `terraform init` fetch each provider binary ONCE
# into infra/terraform/.plugin-cache/ and share it across every stack.
# infra/terraform/versions.tf is the canonical version contract; stacks MUST
# match it (make tf-versions-check).
TF_ROOT := infra/terraform
TF_PLUGIN_CACHE := $(abspath $(TF_ROOT)/.plugin-cache)
TF := TF_PLUGIN_CACHE_DIR=$(TF_PLUGIN_CACHE) terraform

tf-cache-setup:
	@mkdir -p $(TF_PLUGIN_CACHE)
	@echo "TF plugin cache: $(TF_PLUGIN_CACHE)"

# Populate the cache with every provider in versions.tf in a single init.
# Run once after cloning (or after bumping a provider version).
tf-cache-warm: tf-cache-setup
	@echo "=== WARMING SHARED PLUGIN CACHE ==="
	@cd $(TF_ROOT) && $(TF) init -backend=false
	@echo "=== CACHE WARM — providers shared across all stacks ==="
	@echo "Cache dir: $(TF_PLUGIN_CACHE)"

# Initialise a single stack using the shared cache (no per-stack re-download).
#   make tf-init STACK=stacks/aws-vllm
tf-init: tf-cache-setup
	@test -n "$(STACK)" || { echo "Usage: make tf-init STACK=stacks/<name>"; exit 2; }
	@test -d $(TF_ROOT)/$(STACK) || { echo "No such stack: $(TF_ROOT)/$(STACK)"; exit 2; }
	@cd $(TF_ROOT)/$(STACK) && $(TF) init

# State-free initialization for release Azure stacks. The scoped cleaner only
# removes test-generated tfvars carrying its marker; operator files and state
# are preserved. Validate-only proves routing without downloading providers.
tf-init-local: tf-cache-setup
	@case "$(STACK)" in stacks/azure-vllm|stacks/azure-llamacpp|stacks/azure-container-app-vllm|stacks/azure-container-app-environment) ;; *) echo "Usage: make tf-init-local STACK=stacks/azure-vllm|stacks/azure-llamacpp|stacks/azure-container-app-vllm|stacks/azure-container-app-environment TF_INIT_LOCAL_VALIDATE_ONLY=0|1"; exit 2;; esac
	@$(UV) run python scripts/clean_terraform_test_artifacts.py "$(TF_ROOT)/$(STACK)"
	@if [ "$(TF_INIT_LOCAL_VALIDATE_ONLY)" = "1" ]; then echo "tf-init-local validate-only stack=$(STACK)"; exit 0; fi; \
		RESOURCE_ROOT="$$( $(UV) run python scripts/resource_arbiter.py root )"; \
		TF_LOCAL_PARENT="$$RESOURCE_ROOT/terraform-init"; \
		mkdir -p "$$TF_LOCAL_PARENT"; \
		TF_LOCAL_DATA_DIR="$$(mktemp -d "$$TF_LOCAL_PARENT/$(subst /,-,$(STACK)).XXXXXX")"; \
		cleanup_tf_local() { rm -rf "$$TF_LOCAL_DATA_DIR"; }; \
		trap cleanup_tf_local EXIT INT TERM; \
		cd "$(TF_ROOT)/$(STACK)" && \
		TF_PLUGIN_CACHE_DIR="$(TF_PLUGIN_CACHE)" TF_DATA_DIR="$$TF_LOCAL_DATA_DIR" terraform init -backend=false && \
		TF_PLUGIN_CACHE_DIR="$(TF_PLUGIN_CACHE)" TF_DATA_DIR="$$TF_LOCAL_DATA_DIR" terraform validate

# Validates a single stack against the shared cache.
#   make tf-validate STACK=stacks/aws-vllm
tf-validate: tf-cache-setup
	@test -n "$(STACK)" || { echo "Usage: make tf-validate STACK=stacks/<name>"; exit 2; }
	@test -d $(TF_ROOT)/$(STACK) || { echo "No such stack: $(TF_ROOT)/$(STACK)"; exit 2; }
	@cd $(TF_ROOT)/$(STACK) && $(TF) validate

# Enforces the canonical provider-version contract (infra/terraform/versions.tf).
# Every stack's required_providers must match. Run before commit / in CI.
tf-versions-check:
	@$(PYTHON) scripts/check_tf_provider_versions.py

# Removes the shared cache (provider binaries); regenerated by tf-cache-warm.
tf-clean:
	@mkdir -p $(TF_PLUGIN_CACHE)
	@find $(TF_PLUGIN_CACHE) -mindepth 1 ! -name .gitkeep -exec rm -rf {} +
	@echo "Removed cached providers from $(TF_PLUGIN_CACHE); preserved .gitkeep"

# --- Presentation deck ---
#   make deck            — build the reveal.js deck (generate deck-data.json + honesty check)
#   make deck-serve      — resolve {{TOKEN}}s into a scratch copy (/tmp/gludd-deck-preview)
#                          and serve THAT — the tracked template is never modified
#   make deck-preview    — build the same resolved scratch copy without serving
#                          (non-interactive; useful for CI/verification)
#   make deck-data       — collect live project data → deck-data.json (no render)
#   make deck-honesty    — lint the deck HTML for banned marketing tokens
DECK_DIR := docs/presentation/deck
DECK_DATA := docs/presentation/deck-data.json
PRESENTATION_VENDOR_VALIDATE_ONLY ?= 1
PRESENTATION_BROWSER_VALIDATE_ONLY ?= 1
PRESENTATION_BROWSER_ROOT ?= /tmp/gludd-playwright-browsers
PRESENTATION_BROWSER_OUTPUT ?= /tmp/gludd-presentation-browser
PRESENTATION_BROWSER_TIMEOUT ?= 300

vendor-presentation-assets:
	@case "$(PRESENTATION_VENDOR_VALIDATE_ONLY)" in 0|1) ;; *) echo "PRESENTATION_VENDOR_VALIDATE_ONLY must be 0 or 1"; exit 2;; esac
	@$(UV) run python scripts/vendor_presentation_assets.py $(if $(filter 1,$(PRESENTATION_VENDOR_VALIDATE_ONLY)),--validate-only,--refresh)

presentation-browser-test:
	@case "$(PRESENTATION_BROWSER_VALIDATE_ONLY)" in 0|1) ;; *) echo "PRESENTATION_BROWSER_VALIDATE_ONLY must be 0 or 1"; exit 2;; esac
	@$(UV) run python scripts/run_presentation_browser_tests.py \
		$(if $(filter 1,$(PRESENTATION_BROWSER_VALIDATE_ONLY)),--validate-only,--run) \
		--browser-root "$(PRESENTATION_BROWSER_ROOT)" \
		--output-root "$(PRESENTATION_BROWSER_OUTPUT)" \
		--timeout-seconds "$(PRESENTATION_BROWSER_TIMEOUT)"

deck:
	@echo "=== BUILDING DECK ==="
	@$(UV) run python3 scripts/build_deck.py
	@echo "=== DECK BUILT ==="
	@echo "View: make deck-serve  or  open $(DECK_DIR)/index.html"

deck-build: deck
	@echo "=== REGENERATING DECK HTML FROM LIVE DATA ==="
	@$(UV) run python3 scripts/build_deck.py --build
	@echo "=== DECK HTML REGENERATED ==="

# Serves a token-RESOLVED copy of the deck (built into /tmp/gludd-deck-preview)
# so the local preview shows real numbers, same as the published Pages site —
# without ever writing to the tracked docs/presentation/deck/index.html template.
deck-serve:
	@echo "Serving deck at http://localhost:8080/ (resolved preview copy; tracked template untouched)"
	@$(UV) run python3 scripts/build_deck.py --serve

# Non-interactive counterpart to deck-serve: builds the resolved scratch copy
# in /tmp/gludd-deck-preview without starting the HTTP server. Use this to
# verify token substitution (e.g. in CI or scripted checks) without blocking.
deck-preview:
	@$(UV) run python3 scripts/build_deck.py --preview

# Remove the legacy SVG artifacts from the deck assets dir (now replaced by inline Mermaid).
# Physically deletes the files and the assets/ dir if it becomes empty.
deck-clean-assets:
	@rm -f $(DECK_DIR)/assets/architecture.svg $(DECK_DIR)/assets/event-loop.svg $(DECK_DIR)/assets/security-layers.svg
	@if [ -d "$(DECK_DIR)/assets" ] && [ -z "$$(ls -A $(DECK_DIR)/assets)" ]; then rmdir $(DECK_DIR)/assets && echo "removed empty dir: $(DECK_DIR)/assets"; fi
	@echo "deck assets cleaned"

deck-data:
	@$(UV) run python3 scripts/build_deck.py --data

deck-honesty:
	@$(UV) run python3 scripts/build_deck.py --check

# --- One-shot guardrail: all enforcement checks in a single target ---
.PHONY: check-all-guardrails
check-all-guardrails: check-plugin-heartbeats check-test-env-writes check-clean-tree-status
	@echo "All guardrails active"

.PHONY: check-brace-balance
check-brace-balance:
	@$(UV) run python scripts/check_brace_balance.py $(PLUGIN)

check-clean-tree-status:
	@$(UV) run python3 scripts/check_clean_tree.py

# --------------------------------------------------------------------------- #
# SearXNG research backend — privacy-respecting meta-search
# --------------------------------------------------------------------------- #
SEARXNG_DIR := infra/searxng
SEARXNG_URL ?= http://localhost:8080

searx-up:
	@if ! command -v docker >/dev/null 2>&1; then echo "docker not found"; exit 1; fi
	@cd "$(SEARXNG_DIR)" && docker compose up -d
	@echo "SearXNG starting at $(SEARXNG_URL)"
	@echo "Health check:  make searx-test"

searx-down:
	@if ! command -v docker >/dev/null 2>&1; then echo "docker not found"; exit 1; fi
	@cd "$(SEARXNG_DIR)" && docker compose down -v
	@echo "SearXNG stopped, volumes removed"

searx-test:
	@URL="$(SEARXNG_URL)/search?q=test&format=json"; \
	code=$$(curl -s -o /tmp/gludd-searx-test.json -w '%{http_code}' "$$URL" 2>&1); \
	if [ "$$code" = "200" ]; then \
		count=$$($(PYTHON) -c "import json;d=json.load(open('/tmp/gludd-searx-test.json'));print(len(d.get('results',[])))" 2>/dev/null); \
		echo "SearXNG OK (HTTP $$code, $$count results)"; \
	else \
		echo "SearXNG FAIL: HTTP $$code (is it running? try 'make searx-up')"; \
		exit 1; \
	fi

searx-start:
	@$(PYTHON) -m general_ludd.cli searx start

searx-stop:
	@$(PYTHON) -m general_ludd.cli searx stop

searx-status:
	@$(PYTHON) -m general_ludd.cli searx status

searx-install:
	@$(PYTHON) -c "from general_ludd.searx.install import ensure_searx_installed; ensure_searx_installed(); print('OK')"

# --- Service Discovery ---
test-service-discovery:
	@$(UV) run python -m pytest tests/unit/test_searx_client.py tests/unit/test_service_catalog.py tests/unit/test_service_discovery_pipeline.py -v

service-discover:
	@$(UV) run python -m general_ludd.cli.service_commands discover

service-catalog:
	@$(UV) run python -m general_ludd.cli.service_commands catalog

# --- Networking Role & Scapy Adapter ---
# Lint the networking Ansible role (graceful if role does not exist yet)
networking-role-lint:
	@NETWORKING_ROLE=collections/ansible_collections/general_ludd/agent/roles/networking; \
	if [ -d "$$NETWORKING_ROLE" ]; then \
		$(UV) run ansible-lint "$$NETWORKING_ROLE" || true; \
	else \
		echo "networking role not found (skipping lint)"; \
	fi

# Check YAML syntax for all networking role files
networking-role-syntax:
	@NETWORKING_ROLE=collections/ansible_collections/general_ludd/agent/roles/networking; \
	if [ -d "$$NETWORKING_ROLE" ]; then \
		for f in $$(find "$$NETWORKING_ROLE" -name '*.yml' -o -name '*.yaml' 2>/dev/null); do \
			echo "Checking $$f..."; \
			$(UV) run python -c "import yaml; yaml.safe_load(open('$$f'))" || exit 1; \
		done; \
		echo "networking role YAML syntax OK"; \
	else \
		echo "networking role not found (skipping syntax check)"; \
	fi

# Run scapy adapter unit tests (skip if scapy not installed)
test-scapy-adapter:
	@if $(UV) run python -c "import scapy" 2>/dev/null; then \
		if [ -n "$(TESTFILE)" ]; then \
			$(UV) run python -m pytest $(TESTFILE) -v; \
		elif [ -f tests/unit/test_scapy_adapter.py ]; then \
			$(UV) run python -m pytest tests/unit/test_scapy_adapter.py -v; \
		else \
			echo "no scapy adapter test file found"; \
		fi; \
	else \
		echo "scapy not installed — skipping scapy adapter tests"; \
	fi
