---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Include sdr_capture"
      ansible.builtin.include_role:
        name: "sdr_capture"
      vars:
        sdr_capture_enabled: false
