"""Tests for narrowly scoped Terraform test-artifact cleanup."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "clean_terraform_test_artifacts.py"
GENERATED_MARKER = "# Auto-generated by test_terraform_all_stacks_valid.py"


def _run_cleaner(stack_dir: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(stack_dir)],
        cwd=ROOT,
        check=False,
        text=True,
        capture_output=True,
    )


def test_cleaner_removes_only_marked_generated_tfvars(tmp_path: Path) -> None:
    stack_dir = tmp_path / "stack"
    stack_dir.mkdir()
    generated = stack_dir / "terraform.auto.tfvars"
    generated.write_text(
        f"{GENERATED_MARKER}\n# DO NOT COMMIT\nmodel = \"test\"\n",
        encoding="utf-8",
    )

    result = _run_cleaner(stack_dir)

    assert result.returncode == 0, result.stdout + result.stderr
    assert "removed=1" in result.stdout
    assert not generated.exists()


def test_cleaner_preserves_operator_authored_tfvars(tmp_path: Path) -> None:
    stack_dir = tmp_path / "stack"
    stack_dir.mkdir()
    operator_tfvars = stack_dir / "terraform.auto.tfvars"
    operator_tfvars.write_text('region = "eastus"\n', encoding="utf-8")

    result = _run_cleaner(stack_dir)

    assert result.returncode == 0, result.stdout + result.stderr
    assert "removed=0" in result.stdout
    assert operator_tfvars.read_text(encoding="utf-8") == 'region = "eastus"\n'
