#!/usr/bin/env python3
"""ssl_config — SSL config generator, Mozilla cipher profiles, cert validation."""
import argparse
import datetime
import json
import ssl
import sys
from pathlib import Path


MOZILLA_CIPHER_PROFILES = {
    "modern": {
        "description": "TLS 1.3 only, AEAD ciphers, no legacy",
        "tls_versions": ["TLSv1.3"],
        "ciphers": (
            "TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:"
            "TLS_CHACHA20_POLY1305_SHA256"
        ),
        "ssl_protocols": "TLSv1.3",
        "ssl_prefer_server_ciphers": "off",
        "dhparam": 2048,
        "curves": "X25519:prime256v1:X448:secp521r1:secp384r1",
        "hsts": True,
        "ocsp_stapling": True,
    },
    "intermediate": {
        "description": "TLS 1.2+, ECDHE forward secrecy, no CBC",
        "tls_versions": ["TLSv1.2", "TLSv1.3"],
        "ciphers": (
            "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:"
            "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:"
            "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305"
        ),
        "ssl_protocols": "TLSv1.2 TLSv1.3",
        "ssl_prefer_server_ciphers": "on",
        "dhparam": 2048,
        "curves": "X25519:prime256v1:secp384r1",
        "hsts": True,
        "ocsp_stapling": True,
    },
    "old": {
        "description": "TLS 1.0+ (legacy client compatibility, NOT recommended)",
        "tls_versions": ["TLSv1.0", "TLSv1.1", "TLSv1.2", "TLSv1.3"],
        "ciphers": (
            "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:"
            "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:"
            "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:"
            "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
        ),
        "ssl_protocols": "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3",
        "ssl_prefer_server_ciphers": "on",
        "dhparam": 2048,
        "curves": "prime256v1:secp384r1",
        "hsts": True,
        "ocsp_stapling": False,
    },
}


def generate_nginx_ssl_config(profile, min_tls, hsts_max_age):
    prof = MOZILLA_CIPHER_PROFILES.get(profile)
    if not prof:
        raise ValueError(f"Unknown profile: {profile}")

    lines = [
        "# Generated by ssl_config.py — Mozilla {profile} profile",
        "# {description}",
        "",
        f"ssl_protocols {prof['ssl_protocols']};",
        f"ssl_ciphers {prof['ciphers']};",
        f"ssl_prefer_server_ciphers {prof['ssl_prefer_server_ciphers']};",
        f"ssl_ecdh_curve {prof['curves']};",
        "",
        "# Session cache",
        "ssl_session_cache shared:SSL:10m;",
        "ssl_session_tickets off;",
        "",
        "# DH parameters",
        f"ssl_dhparam /etc/nginx/dhparam.pem;",
        "",
    ]

    if prof["ocsp_stapling"]:
        lines.extend([
            "# OCSP Stapling",
            "ssl_stapling on;",
            "ssl_stapling_verify on;",
            f"ssl_trusted_certificate /etc/nginx/ssl/chain.pem;",
            "resolver 8.8.8.8 8.8.4.4 valid=300s;",
            "resolver_timeout 5s;",
            "",
        ])

    if prof["hsts"]:
        lines.extend([
            "# HSTS",
            f"add_header Strict-Transport-Security \"max-age={hsts_max_age}; includeSubDomains\" always;",
            "",
        ])

    lines.extend([
        "# Security headers",
        "add_header X-Frame-Options DENY always;",
        "add_header X-Content-Type-Options nosniff always;",
        "add_header X-XSS-Protection \"1; mode=block\" always;",
    ])

    return "\n".join(lines)


def validate_certificate(cert_path, key_path=None):
    result = {"cert": str(cert_path), "valid": True, "errors": []}

    try:
        cert_pem = Path(str(cert_path)).read_text()
    except Exception as e:
        result["valid"] = False
        result["errors"].append(f"Cannot read cert: {e}")
        return result

    if "BEGIN CERTIFICATE" not in cert_pem:
        result["valid"] = False
        result["errors"].append("File does not contain a PEM certificate")

    if key_path:
        try:
            key_pem = Path(str(key_path)).read_text()
        except Exception as e:
            result["errors"].append(f"Cannot read key: {e}")
        if "BEGIN PRIVATE KEY" not in key_pem and "BEGIN RSA PRIVATE KEY" not in key_pem:
            result["errors"].append("Key file does not contain a PEM private key")

    return result


def certificate_info(cert_path):
    info = {"subject": {}, "issuer": {}, "not_before": None, "not_after": None,
            "serial": None, "days_remaining": None}
    try:
        from cryptography import x509
        from cryptography.x509.oid import NameOID
        cert_pem = Path(str(cert_path)).read_bytes()
        cert = x509.load_pem_x509_certificate(cert_pem)
        info["subject"] = {attr.oid._name: attr.value
                           for attr in cert.subject
                           if hasattr(attr.oid, '_name')}
        info["issuer"] = {attr.oid._name: attr.value
                          for attr in cert.issuer
                          if hasattr(attr.oid, '_name')}
        info["serial"] = str(cert.serial_number)
        info["not_before"] = cert.not_valid_before_utc.isoformat()
        info["not_after"] = cert.not_valid_after_utc.isoformat()
        info["days_remaining"] = (
            cert.not_valid_after_utc - datetime.datetime.now(datetime.timezone.utc)
        ).days
    except ImportError:
        info["_warning"] = "cryptography package not installed; limited info"
    except Exception as e:
        info["_error"] = str(e)
    return info


def main():
    parser = argparse.ArgumentParser(description="ssl_config tool")
    sub = parser.add_subparsers(dest="command")

    gen_p = sub.add_parser("generate")
    gen_p.add_argument("--profile", choices=["modern", "intermediate", "old"],
                       default="intermediate")
    gen_p.add_argument("--min-tls", default="1.2")
    gen_p.add_argument("--hsts-max-age", type=int, default=31536000)
    gen_p.add_argument("--output", help="file path to write config snippet")

    val_p = sub.add_parser("validate")
    val_p.add_argument("--cert", required=True, help="path to certificate file")
    val_p.add_argument("--key", help="path to private key file")

    info_p = sub.add_parser("info")
    info_p.add_argument("--cert", required=True, help="path to certificate file")

    args = parser.parse_args()

    if args.command == "generate":
        config = generate_nginx_ssl_config(args.profile, args.min_tls, args.hsts_max_age)
        if args.output:
            Path(args.output).write_text(config)
            print(f"Written to {args.output}")
        else:
            print(config)

    elif args.command == "validate":
        result = validate_certificate(args.cert, args.key)
        print(json.dumps(result, indent=2, default=str))
        sys.exit(0 if result["valid"] else 1)

    elif args.command == "info":
        info = certificate_info(args.cert)
        print(json.dumps(info, indent=2, default=str))


if __name__ == "__main__":
    main()
